// root/main.c

/*
 * PSn00bSDK - OBJ Model Renderer (GTE version)
 *
 * Current features:
 * - Filled triangle rendering
 * - OBJ importer support
 * - Runtime scaling (debug_scale, a live fixed-point multiplier layered
 *   over every scene object's own authored scale - see draw_scene())
 * - XYZ rotation (GTE-driven)
 * - GTE perspective projection
 * - Backface culling (same winding test gte_nclip computes in hardware,
 *   done in software against cached screen coords - see the per-vertex
 *   transform caching bullet below)
 * - GTE-rotated face normals for flat lighting
 * - GTE-rotated vertex normals for Gouraud lighting
 * - Textured polygon rendering (POLY_FT3)
 * - Multi-CLUT palette-swap textures (stacked CLUT rows in one TIM,
 *   base row is per-object scene data, live-nudged via SQUARE/CIRCLE in
 *   the camera control schema - hold L2, see update())
 * - GPU Ordering Table (OT_LEN buckets - see draw_object_into_ot()):
 *   every triangle from every visible object is inserted into ONE shared
 *   OT keyed by its own gte_avsz3()-derived depth bucket; the GPU's
 *   linked-list walk (DrawOTag()) does the back-to-front sort, replacing
 *   the old CPU insertion sort entirely
 * - Per-vertex transform caching (transform_object_vertices()): each
 *   unique model vertex is rotated/translated/projected through the GTE
 *   exactly ONCE per object per frame (gte_rtps), cached, and looked up
 *   per triangle corner - instead of re-running the GTE's triple
 *   transform (gte_rtpt) for every triangle a vertex appears in
 * - Per-object frustum culling (object_is_culled()): projects each
 *   object's own bounding sphere (centre + two radius-offset edge
 *   points) through its real composed matrix and rejects it before
 *   touching any of its triangles if it's behind the near plane or
 *   entirely outside the 320x240 screen bounds
 * - Scene loading (scenes/*_/scene.json -> generated/scene_*.c): places
 *   named model instances with their own pos/rot/scale/palette
 * - Multiple simultaneous models (generated/model_registry.c), resolved
 *   by name per scene object instead of one hand-#include'd model
 * - Double buffering
 * - Single-controller input (see update()): holding L2 switches pad 1
 *   from the debug transform schema to the camera schema
 *
 */

// Toolchain paths (set these as env vars on your machine, not hardcoded
// here - PATH, PSN00BPS1_TOOLS, PSN00BSDK_LIBS). See py_convert_assets.py,
// py_convert_textures.py and py_convert_scenes.py for the asset-side
// equivalents.

#include <stdio.h>
#include <string.h>
#include <sys/types.h>

#include <psxetc.h>
#include <psxgte.h>
#include <psxgpu.h>
#include <psxapi.h>   // BIOS API: InitPAD, StartPAD, ChangeClearPAD, etc.
#include <psxpad.h>   // PadButton enums (PAD_UP, PAD_DOWN, PAD_LEFT, PAD_RIGHT)
#include <inline_c.h> // GTE macros (gte_ldv0, gte_rtpt, gte_nclip, etc.)


// Every discovered assets/<name>/<name>.obj, baked in unconditionally.
// Defines MODEL_TRI/MODEL_DEF (via model_common.h), each <name>_model*
// array, and modelRegistry[]/modelRegistryCount. See py_convert_assets.py.
#include "generated/models_all.h"

// Concatenated texture blob (all TIMs back-to-back) + offset/length table,
// both generated by py_convert_textures.py. tex_blob_start is the base
// pointer every texBlobMaterialTable offset is relative to. TEX_BLOB_ENTRY
// and the tex_blob_start/end + texBlobMaterialTable externs live in
// generated/tex_blob_table.h, shared by tex_blob_table.c and main.c.
#include "generated/tex_blob_table.h"

// Every discovered scenes/*/scene.json, baked in unconditionally. Defines
// SCENE_OBJECT/SCENE_DEF (via scene_common.h), each scene's own
// <name>_objects[]/<name>_objectCount, and sceneRegistry[]/
// sceneRegistryCount. See py_convert_scenes.py. Scene objects resolve
// model NAMES against modelRegistry[] at RUNTIME (load_scene(), below),
// not at compile time, so there's no real build-order dependency on
// models_all.h above.
#include "generated/scenes_all.h"

// Runtime texture table - one resolved TIM_IMAGE per material name found
// in the blob, built once in load_textures() by walking
// texBlobMaterialTable and calling GetTimInfo() on each blob slice. Fixed
// size (no heap on PS1); bump MAX_TEXTURES if this ceiling is ever hit.
#define MAX_TEXTURES 32

typedef struct
{
    const char *material;
    TIM_IMAGE tim;
    uint8_t loaded;

    // Stacked CLUT row count (1 for a plain single-palette texture).
    // draw_object_into_ot() clamps a placed object's palette row against
    // this before adding it to tim.crect->y, so an out-of-range row can't
    // read into another texture's VRAM data.
    unsigned int paletteCount;
} MODEL_TEXTURE;

static MODEL_TEXTURE textureTable[MAX_TEXTURES];
static unsigned int textureTableCount = 0;

// Per-model material name table (modelRegistry[].materialNames/
// materialCount, emitted by py_convert_assets.py from each .obj's usemtl
// lines). tri->material indexes THAT model's own materialNames;
// build_triangle_texture_cache() resolves that name against
// textureTable[] to find the actual TIM_IMAGE, if any - this indirection
// is what lets material index 0 mean different textures per model.



// Screen consts (for model placement)
#define DISPLAY_W 320
#define DISPLAY_H 240

#define SCREEN_CX (DISPLAY_W / 2)
#define SCREEN_CY (DISPLAY_H / 2)



// ============================================================
// COORDINATE SYSTEM - FINALISED (v4, verified via arrow.obj dual-tip test)
// ============================================================
// Source assets are authored in Blender, exported with Forward=-Z, Up=Y.
// The converter (py_convert_assets.py, get_split_vertex()) remaps every
// vertex/normal at export time so that:
//
//   renderer_X =  Blender_X
//   renderer_Y = -Blender_Z
//   renderer_Z = -Blender_Y
//
// Verified with a two-tipped arrow test object: Blender's +Y tip renders
// pointing AWAY from the camera; Blender's +Z tip renders pointing UP on
// screen. A model's Blender-up is screen-up, and its Blender-forward
// (+Y) points away from the camera by default with model_rot = {0,0,0} -
// no per-model rotation offset needed.
//
// Winding/cull sign (draw_object_into_ot()'s gte_nclip/cross check) was
// re-verified against this final mapping: front-facing triangles are
// correctly kept with `if (cross >= 0) continue;` as the reject
// condition. If this coordinate block changes again, re-check that sign
// against the arrow.obj test - it flips whenever an even number of axes
// change sign, and stays put when an odd number do (a mnemonic, not a
// substitute for testing).
//
// Do NOT re-flip or re-derive axes anywhere else in this file. If a
// specific model renders mirrored or backwards, re-test with arrow.obj
// first - the bug is very likely elsewhere (a bad per-model rotation
// default, or that one asset having different OBJ export settings), not
// this coordinate system.
#define CAMERA_DISTANCE 4096
#define FOCAL_LENGTH    256
int fov = FOCAL_LENGTH;
int fov_speed = 10;

// Maximum number of vertices we cache for a transformed model.
// Bumped from 127 -> 512 for Option B vertex-splitting at seams: a split
// model's vertex count can exceed its raw OBJ 'v' count (each hard-edge
// seam duplicates a position per distinct normal/UV it's used with). Check
// the converter's printed "Split vertex count" against this on each
// model swap - if a model ever exceeds 512, bump this again.
#define MAX_MODEL_VERTS 512

// Maximum number of triangles we cache for sorting/lighting, PER MODEL.
#define MAX_MODEL_TRIS 512//256

// Ceiling on how many distinct models (modelRegistry[] entries) get their
// own triangle/texture cache built at load time - see
// build_triangle_texture_cache(). Bump if assets/ grows past this many
// distinct model folders; modelRegistryCount is clamped against it
// rather than trusted blindly, same fail-safe pattern as MAX_TEXTURES.
#define MAX_MODELS 16

// Ceiling on how many objects a single scene can place at once (fixed-
// size arrays, no heap on PS1). Bump if a scene needs more; scene
// object counts are clamped against this in load_scene(), same pattern
// as MAX_MODELS/MAX_TEXTURES.
#define MAX_SCENE_OBJECTS 32

// ------------------------------------------------------------
// GPU Ordering Table
// ------------------------------------------------------------
// Number of depth buckets in the OT. Each bucket holds a linked list of
// primitives at roughly that depth; DrawOTag() walks every bucket
// farthest-to-nearest in hardware - this is what sorts the frame (see
// draw_object_into_ot()). More buckets = finer back-to-front resolution
// at the cost of a bigger ClearOTagR() per frame and more static RAM;
// bump if far-apart triangles start visibly fighting.
#define OT_LEN 1024

// Right-shift applied to the raw gte_avsz3()/gte_stotz() depth value
// before clamping it into an OT bucket index. Per inline_c.h, gte_avsz3()
// computes OTZ = ZSF3*(SZ1+SZ2+SZ3)/4096 - ZSF3 itself is set by
// InitGeom() (not exposed as a header macro, so its default isn't
// visible here), so the exact numeric range OTZ lands in for this
// project's camera/model scale is still empirical. TUNE THIS: raise the
// shift if distant geometry clumps into the last bucket; lower it if
// nearby triangles land in too few buckets.
#define OT_Z_SHIFT 2

// Upper bound on triangles insertable into the OT in a single frame,
// across every visible object. primBytesRemaining enforces this as a
// hard runtime cap - an over-budget scene drops triangles (reported via
// debug_text()'s PRIM_OVERFLOW counter) instead of overrunning the
// primitive arena.
#define MAX_PRIMS_PER_FRAME 4096



// Double buffering
// Define display/draw environments for double buffering
DISPENV disp[2];
DRAWENV draw[2];
int db;

// The Ordering Table itself, double-buffered like disp/draw so the GPU
// can still be walking last frame's OT (DrawOTag()) while the CPU fills
// the OTHER buffer's OT for the next frame.
static uint32_t ot[2][OT_LEN];

// Primitive packet storage backing the OT above. ClearOTagR()/addPrim()
// only manage the ot[] linked-list structure - the actual POLY_F3/POLY_G3/
// POLY_FT3 data has to live somewhere that survives until DrawOTag()
// finishes walking it, so every triangle gets its OWN slot, bump-
// allocated from this arena via nextpri/primBytesRemaining below. Sized
// as MAX_PRIMS_PER_FRAME worst-case POLY_FT3s (the largest of the three
// types); the bump allocator advances by each primitive's real size, so
// the byte budget is correct regardless of the actual type mix.
static char primBuffer[2][MAX_PRIMS_PER_FRAME * sizeof(POLY_FT3)];

// Bump-allocator cursor into primBuffer[db] - reset at the top of every
// main() loop iteration, advanced by sizeof(<primitive type>) each time
// draw_object_into_ot() allocates one.
static char *nextpri;

// Remaining bytes in primBuffer[db] this frame - checked against
// sizeof(POLY_FT3) (the largest type) before every allocation so an
// over-budget scene drops triangles instead of overrunning the arena.
static long primBytesRemaining;

// Debug counters, reset once per frame in draw_scene()/main() - see
// debug_text().
static unsigned int visibleObjectCount = 0;
static unsigned int culledObjectCount = 0;
static unsigned int primOverflowCount = 0;



// Gamepad buffers (BIOS pad driver style)
static unsigned char padbuf[2][34];

// Previous frame's raw pad state, used for edge detection on toggle
// buttons (TRIANGLE/SQUARE) so a held button doesn't re-toggle every
// single frame (60x/sec) - only the released->pressed transition fires.
unsigned short prevPadRaw = 0xFFFF; // all-released, matches BIOS idle state

// Which control schema is currently selected (L2 held = camera schema,
// released = debug transform schema) - set in update(), read by
// debug_text() so the active schema is visible on screen.
static int cameraSchemaActive = 0;



// ------------------------------------------------------------
// Camera
// ------------------------------------------------------------
// The GTE only transforms vertices relative to a fixed origin, so
// "moving the camera" means translating/rotating vertices by the inverse
// of the camera's transform - accumulated in one shared CAMERA struct
// (independent of any model's own transform) so multiple placed models
// can share one camera and camera movement only touches this struct.
typedef struct
{
    VECTOR  pos;   // world-space position
    SVECTOR rot;   // 12-bit fixed-point angles (4096 = 360 degrees), same format as model_rot
} CAMERA;

// Compiled-in fallback if sceneRegistryCount is ever 0 (e.g. scenes/ is
// empty) - load_scene() overwrites this from the active scene's own
// "camera" block otherwise.
CAMERA camera = { { 0, 0, -CAMERA_DISTANCE }, { 0, 0, 0 } };

const int32_t CAMERA_MOVE_SPEED = 32;   // world units per frame, same fixed-point scale as modelVerts
const uint16_t CAMERA_ROT_SPEED = 22;   // matches ROT_SPEED below for consistency

// Camera's own view matrix - rotation + translation for -camera.pos,
// rebuilt once per frame in update_camera_matrix(). Composed with each
// placed object's own world matrix in update_object_world_and_compose()
// rather than fed to the GTE directly.
MATRIX camera_view_matrix;

// Composed matrix (camera_view_matrix * world_matrix) actually fed to the
// GTE each frame - kept separate from world_matrix so world_matrix always
// represents only the CURRENT object's own transform (reused as scratch
// across however many objects the scene places, one at a time).
MATRIX composed_matrix;



// ------------------------------------------------------------
// Debug transform - a global offset/multiplier layered on top of EVERY
// scene object's own authored pos/rot/scale (see draw_scene()), driven
// by pad 1. Purely a live testing knob - e.g. spin the whole scene to
// eyeball lighting, or nudge every object at once without reconverting.
// ------------------------------------------------------------
int debug_scale = 4096;                 // fixed-point multiplier, 4096 == 1.0x
const uint16_t SCALE_SPEED = 64;        // ~1.5% of 1.0x per frame
const uint8_t ROT_SPEED = 22;

// XYZ rotation angles, fed straight into RotMatrix() as an SVECTOR.
// 12-bit fixed-point angle format (4096 = 360 degrees).
SVECTOR model_rot = { 0, 0, 0 };

// Debug world-position OFFSET, added to every scene object's own pos.
// Zero by default (no pad control wired to it today).
VECTOR model_pos = { 0, 0, 0 };

// GTE rotation matrix, rebuilt once per object per frame in
// update_object_world_and_compose(). Represents ONLY that object's own
// transform - the camera is composed in separately (already built in
// update_camera_matrix()).
MATRIX world_matrix;

// Rotated face normal cache (one per triangle, post-transform), reused
// as shared scratch across every drawn object - draw_scene() always
// fully finishes one object (rotate -> cull -> draw) before moving to
// the next, so nothing here needs to survive past a single object's turn.
// Index-matches a model's faceNormals/tris 1:1.
SVECTOR transformedNormals[MAX_MODEL_TRIS];

// Rotated VERTEX normal cache, same shared-scratch reasoning as
// transformedNormals above. Index-matches vertNormals/verts 1:1; looked
// up per-triangle-corner in draw_object_into_ot() for Gouraud shading.
SVECTOR transformedVertNormals[MAX_MODEL_VERTS];

// Cached per-vertex screen-space projection, one entry per unique model
// vertex - built ONCE per object per frame by transform_object_vertices()
// (gte_ldv0 + gte_rtps, the single-vertex transform), then looked up per
// triangle CORNER in draw_object_into_ot() instead of re-running a fresh
// gte_rtpt() per TRIANGLE. Since most vertices are shared by more than
// one triangle, this cuts the GTE's most expensive op (rotate+translate+
// perspective) from 3x triangleCount down to just vertCount calls per
// object. Same shared-scratch reasoning as transformedNormals above.
static DVECTOR transformedScreenXY[MAX_MODEL_VERTS];
static uint32_t transformedScreenSZ[MAX_MODEL_VERTS];

// Per-model (not per-instance) triangle -> texture lookup cache, indexed
// [modelRegistry index][triangle index]. Filled once at startup (not
// per-frame) by build_triangle_texture_cache(): resolves
// materialNames[tri->material] against textureTable[] by name, or NULL
// if that material has no texture (flat-colour materials fall back to
// flat/Gouraud instead of forcing POLY_FT3).
static MODEL_TEXTURE *modelTriTextureCache[MAX_MODELS][MAX_MODEL_TRIS];

// Which baked scene (sceneRegistry[]) is currently active. 0 = first
// discovered scenes/*/scene.json (alphabetical, see py_convert_scenes.py).
// Nothing in the render path assumes a fixed scene index, so a future
// runtime scene switch just needs to change this.
unsigned int activeSceneIndex = 0;

// Set by load_scene(): how many of sceneRegistry[activeSceneIndex]'s
// objects actually get drawn (its objectCount, clamped to MAX_SCENE_OBJECTS).
static unsigned int activeSceneObjectCount = 0;

// Set by load_scene(): sceneObjectModelIndex[i] is the modelRegistry[]
// index the i'th scene object's "model" name resolved to, or -1 if no
// such model exists (e.g. a typo'd or not-yet-created name) - resolved
// ONCE at scene load, not per-frame; draw_scene() skips unresolved
// objects instead of dereferencing NULL.
static int sceneObjectModelIndex[MAX_SCENE_OBJECTS];

// Set by load_scene(): count of objects whose model name didn't
// resolve, surfaced via debug_text()'s UNRESOLVED readout.
static unsigned int sceneUnresolvedCount = 0;



void load_textures(void)
{
    // Parses the concatenated blob (tex_blob_start[], via tex_blob.S's
    // .incbin) using the offset table py_convert_textures.py generated
    // (texBlobMaterialTable[]/texBlobEntryCount). Each entry's
    // offset/length slices out one standalone TIM's bytes; GetTimInfo()
    // parses that slice exactly as it would a standalone .tim file.
    textureTableCount = 0;

    for (unsigned int i = 0; i < texBlobEntryCount && textureTableCount < MAX_TEXTURES; i++)
    {
        const TEX_BLOB_ENTRY *entry = &texBlobMaterialTable[i];

        MODEL_TEXTURE *slot = &textureTable[textureTableCount];
        slot->material = entry->material;
        slot->paletteCount = entry->paletteCount;

        const unsigned char *tim_bytes = tex_blob_start + entry->offset;

        // GetTimInfo() expects a const uint32_t* - the blob is just raw
        // bytes, so this cast doesn't change layout, only how the pointer
        // is typed for the SDK call (same reasoning as the old single-
        // texture face_tim_start[] declaration).
        GetTimInfo((const uint32_t *)tim_bytes, &slot->tim);

        // Upload pixel data to VRAM at the rect the TIM specifies.
        LoadImage(slot->tim.prect, slot->tim.paddr);

        // Upload CLUT data to VRAM ONE ROW AT A TIME rather than as a
        // single N-row block. 4-bit TIMs always carry a CLUT (16 colours);
        // this would be skipped for a 24-bit direct-colour TIM, but we're
        // 4-bit here so crect/caddr are always set for every entry in
        // this blob.
        //
        // A single LoadImage() covering all N rows at once hangs on
        // DuckStation (confirmed by bisection - never reproduced with a
        // single-row CLUT, which is all every texture before multi-CLUT
        // support ever had). Root cause not confirmed, suspected to be an
        // untested DMA block-chunking path in the SDK's _dma_transfer()
        // (libpsn00b/psxgpu/image.c). Splitting into N single-row (16x1)
        // transfers keeps every call on the same shape that already works
        // - if this reproduces on real hardware too, worth reporting
        // upstream to PSn00bSDK.
        if (slot->tim.crect != 0)
        {
            RECT clutRow = *slot->tim.crect;
            clutRow.h = 1;

            for (unsigned int row = 0; row < (unsigned int) slot->tim.crect->h; row++)
            {
                clutRow.y = slot->tim.crect->y + row;

                // caddr is a uint32_t* (2 packed 16-bit colours per word);
                // each 16-colour row is 32 bytes = 8 words, so row k's
                // data starts 8*k words into caddr.
                LoadImage(&clutRow, slot->tim.caddr + (row * 8));
            }
        }

        slot->loaded = 1;
        textureTableCount++;
    }

    // Make sure every upload above has actually landed in VRAM before any
    // draw call tries to sample from them.
    DrawSync(0);
}


// Look up a texture by material name (linear scan - textureTableCount is
// small, typically single digits to low tens, so this is fine to do once
// per triangle at model-load time; see build_triangle_texture_cache()).
static MODEL_TEXTURE *find_texture_by_material(const char *material_name)
{
    for (unsigned int i = 0; i < textureTableCount; i++)
    {
        if (strcmp(textureTable[i].material, material_name) == 0)
            return &textureTable[i];
    }
    return NULL;
}


// Resolves every triangle's material index (into that model's own
// materialNames[]) to an actual texture pointer, once at load time, for
// every model in modelRegistry[]. Triangles whose material has no
// matching textureTable[] entry get NULL, which draw_object_into_ot()
// treats as "use flat/Gouraud shading" instead of a textured path.
void build_triangle_texture_cache(void)
{
    unsigned int modelCount = modelRegistryCount < MAX_MODELS ? modelRegistryCount : MAX_MODELS;

    for (unsigned int m = 0; m < modelCount; m++)
    {
        const MODEL_DEF *model = &modelRegistry[m];
        unsigned int triCount = model->triCount < MAX_MODEL_TRIS ? model->triCount : MAX_MODEL_TRIS;

        for (unsigned int i = 0; i < triCount; i++)
        {
            unsigned char material_index = model->tris[i].material;

            if (material_index >= model->materialCount)
            {
                // Shouldn't happen if py_convert_assets.py and this file
                // agree on MAX_MATERIALS_PER_MODEL, but fail safe to "no
                // texture" rather than reading out of bounds.
                modelTriTextureCache[m][i] = NULL;
                continue;
            }

            const char *material_name = model->materialNames[material_index];
            modelTriTextureCache[m][i] = find_texture_by_material(material_name);
        }
    }
}


// Linear scan over modelRegistry[] by name (small table, fine to do once
// per scene object at scene load). Returns -1 if no model with that name
// was baked in.
static int find_model_index_by_name(const char *name)
{
    for (unsigned int i = 0; i < modelRegistryCount; i++)
    {
        if (strcmp(modelRegistry[i].name, name) == 0)
            return (int)i;
    }
    return -1;
}


// Makes `index` (into sceneRegistry[]) the active scene: pulls its
// camera block into the live CAMERA struct, and resolves every object's
// model-name string against modelRegistry[] ONCE. Safe to call again
// with a different index for a runtime scene switch.
void load_scene(unsigned int index)
{
    activeSceneObjectCount = 0;
    sceneUnresolvedCount = 0;

    if (sceneRegistryCount == 0)
    {
        // No scenes/*/scene.json were discovered at convert time -
        // camera stays at its compiled-in CAMERA default above, and
        // draw_scene() simply has zero objects to draw.
        activeSceneIndex = 0;
        return;
    }

    if (index >= sceneRegistryCount)
        index = 0;

    activeSceneIndex = index;

    const SCENE_DEF *scene = &sceneRegistry[activeSceneIndex];

    camera.pos = scene->cameraPos;
    camera.rot = scene->cameraRot;

    unsigned int objectCount = scene->objectCount < MAX_SCENE_OBJECTS ? scene->objectCount : MAX_SCENE_OBJECTS;

    for (unsigned int i = 0; i < objectCount; i++)
    {
        int idx = find_model_index_by_name(scene->objects[i].model);

        // modelTriTextureCache[] only has slots for modelRegistry[0..
        // MAX_MODELS) - treat a model past that cap as "not found" so
        // draw_scene() never indexes it out of bounds.
        if (idx >= (int)MAX_MODELS)
            idx = -1;

        sceneObjectModelIndex[i] = idx;
        if (idx < 0)
            sceneUnresolvedCount++;
    }

    activeSceneObjectCount = objectCount;
}



void init(void)
{
    // Reset GPU and install ISR subsystem
    ResetGraph(0);

    // Reset and enable the GTE. Must happen before any gte_* macro use.
    InitGeom();

    // Screen-space offset (where projected X=0,Y=0 lands on screen) and
    // projection plane distance. Replaces manual "SCREEN_CX + (vx*FOV)/z"
    // math that would otherwise be done by hand in draw_object_into_ot().
    gte_SetGeomOffset(SCREEN_CX, SCREEN_CY);
    gte_SetGeomScreen(FOCAL_LENGTH);

    // Define display environments, first on top and second on bottom
    SetDefDispEnv(&disp[0], 0,   0, DISPLAY_W, DISPLAY_H);
    SetDefDispEnv(&disp[1], 0, 240, DISPLAY_W, DISPLAY_H);

    // Define drawing environments, first on bottom and second on top
    SetDefDrawEnv(&draw[0], 0, 240, DISPLAY_W, DISPLAY_H);
    SetDefDrawEnv(&draw[1], 0,   0, DISPLAY_W, DISPLAY_H);

    // Set and enable clear colour (green background)
    setRGB0(&draw[0], 0, 96, 0);
    setRGB0(&draw[1], 0, 96, 0);
    draw[0].isbg = 1;
    draw[1].isbg = 1;

    // Clear double buffer counter
    db = 0;

    // Apply the GPU environments
    PutDispEnv(&disp[db]);
    PutDrawEnv(&draw[db]);

    // Load debug font
    FntLoad(960, 0);

    // Open up a debug font text stream of 500 characters
    FntOpen(0, 8, 320, 224, 0, 500);

    // Init pad (BIOS driver). Only padbuf[0] (controller 1) is actually
    // read by update() now - the BIOS pad driver still expects a second
    // buffer to be registered regardless, so padbuf[1] stays wired up
    // but unused for control (see update()'s own comment for the single-
    // controller, L2-modifier control scheme).
    InitPAD(padbuf[0], 34, padbuf[1], 34);
    StartPAD();

    // Don't clear pad data automatically; we read raw bytes ourselves
    ChangeClearPAD(0);

    // Upload every texture in the blob to VRAM and build the runtime
    // texture table. Must happen after ResetGraph() (which resets/clears
    // VRAM) but can otherwise go anywhere in init(); placed last here so
    // pad/font setup isn't visually blocked by it.
    load_textures();

    // Resolve every model's per-triangle material indices to texture
    // pointers once, now that both model data and textureTable[] are
    // loaded. Must run after load_textures(). Adding/removing a model
    // under assets/ picks this up automatically via modelRegistry[] - no
    // main.c edit needed.
    build_triangle_texture_cache();

    // Make the first baked scene (sceneRegistry[0]) active: pulls its
    // camera into `camera`, resolves every object's model name once.
    load_scene(0);
}


void display(void)
{
    // Flip buffer index
    db = !db;

    // Wait for all drawing to complete
    DrawSync(0);

    // Wait for vertical sync to cap the logic to 60fps (or 50 in PAL mode)
    VSync(0);

    // Switch pages
    PutDispEnv(&disp[db]);
    PutDrawEnv(&draw[db]);

    // Enable display output, ResetGraph() disables it by default
    SetDispMask(1);
}


uint8_t use_vertex_light = 1;

// Global "prefer textures when available" toggle. Note this is now a
// PREFERENCE, not a hard switch: draw_object_into_ot() only takes the
// textured path for a triangle when BOTH use_texture is on AND that
// triangle's resolved MODEL_TEXTURE is non-NULL (i.e. its material
// actually has a texture in the blob). A triangle whose material has no
// texture (flat-colour materials) always falls back to flat/Gouraud
// regardless of this flag - see draw_object_into_ot()'s per-triangle
// branch below.
uint8_t use_texture = 0;

// Live palette-row NUDGE, added on top of each placed object's own
// scene-authored base palette row (SCENE_OBJECT.palette) - see
// draw_scene(). Lets you cycle every object's palette together for
// testing (SQUARE/CIRCLE, camera schema - see update()) without having
// to re-author scene.json and reconvert just to preview a different
// row. draw_object_into_ot() clamps the COMBINED (object base + this
// nudge) value per-texture against that texture's own paletteCount, so
// this is safe to leave set higher than any given texture's row count.
uint8_t active_palette = 0;

// Reads ONE controller (padbuf[0]) and updates the debug transform,
// camera, and rendering toggles - both used to be split across two
// physical controllers; now they're two SCHEMAS on one controller,
// switched by holding L2:
//
//   L2 released -> debug transform schema (scale/rotation/FOV/lighting)
//   L2 held     -> camera schema (movement/yaw/palette)
//
// L2 itself is the schema-switch modifier now, so it's no longer
// available as a per-axis button within either schema - its old
// "negative direction" role (paired with R2 for vz-roll and camera-yaw)
// moved to SELECT, which was otherwise unused. Edge-detected toggles
// (TRIANGLE/SQUARE/CIRCLE) share ONE prevPadRaw regardless of schema -
// the active schema only decides which ACTION a press maps to, not how
// edge detection works.
void update(void)
{
    // bytes 2-3 contain button bits (little endian, 0 = pressed).
    // PadButton enums (PAD_UP, etc.) are bit masks where 1 = that
    // button, so we test with ! (pressed when bit is 0).
    unsigned short raw =
        *(unsigned short *)(padbuf[0] + 2);

    cameraSchemaActive = !(raw & PAD_L2);

    if (!cameraSchemaActive)
    {
        // ---- Debug transform schema (L2 released) ----

        // Debug scale - a live fixed-point MULTIPLIER (4096 == 1.0)
        // layered on top of every scene object's own authored scale in
        // draw_scene(). PAD_UP grows it, PAD_DOWN shrinks it.
        if (!(raw & PAD_UP)) debug_scale += SCALE_SPEED;
        if (!(raw & PAD_DOWN)) debug_scale -= SCALE_SPEED;
        if (debug_scale < 64) debug_scale = 64;       // avoid degenerate near-zero/negative scale
        if (debug_scale > 16384) debug_scale = 16384; // avoid overflowing the 16-bit matrix entries at extreme sizes

        // XYZ rotation - 12-bit fixed-point angles (4096 = 360 degrees),
        // so the value space is circular, not bounded. A bitmask wrap
        // (mod 4096, since 4096 is a power of two) keeps rotation
        // continuous through the wraparound instead of snapping/popping
        // at the boundary.
        if (!(raw & PAD_L1)) model_rot.vx -= ROT_SPEED;
        if (!(raw & PAD_R1)) model_rot.vx += ROT_SPEED;
        model_rot.vx &= 4095;

        // SELECT stands in for L2's old "negative" half here, since L2
        // itself is now the schema-switch modifier (see update()'s own
        // comment above).
        if (!(raw & PAD_SELECT)) model_rot.vz -= ROT_SPEED;
        if (!(raw & PAD_R2)) model_rot.vz += ROT_SPEED;
        model_rot.vz &= 4095;

        if (!(raw & PAD_LEFT)) model_rot.vy -= ROT_SPEED;   // rotate left
        if (!(raw & PAD_RIGHT)) model_rot.vy += ROT_SPEED;  // rotate right
        model_rot.vy &= 4095;

        // FOV
        if (!(raw & PAD_CROSS)) fov += fov_speed;
        if (!(raw & PAD_CIRCLE)) fov -= fov_speed;
        if (fov > 65535) fov = 0;
        if (fov < -65535) fov = 65536;

        // Lighting mode toggle - only fires on the frame TRIANGLE goes
        // from released to pressed (bit was 1 last frame, is 0 this
        // frame), not on every frame it's held down.
        if (!(raw & PAD_TRIANGLE) && (prevPadRaw & PAD_TRIANGLE))
            use_vertex_light = use_vertex_light ^ 1;

        // Texture toggle - same edge-detected pattern as above.
        if (!(raw & PAD_SQUARE) && (prevPadRaw & PAD_SQUARE))
            use_texture = use_texture ^ 1;
    }
    else
    {
        // ---- Camera schema (L2 held) ----
        // D-pad: translate on the world X/Z plane (strafe/forward-back).
        // L1/R1: translate on Y (up/down). SELECT/R2: yaw (look left/
        // right) - SELECT stands in for L2's old half of this pair,
        // same reasoning as the debug schema above. Still a simple,
        // direct mapping rather than a proper FPS-style look-at/analog
        // camera (that refinement is still the "Camera" roadmap item).
        if (!(raw & PAD_UP))    camera.pos.vz += CAMERA_MOVE_SPEED; // forward (into the scene)
        if (!(raw & PAD_DOWN))  camera.pos.vz -= CAMERA_MOVE_SPEED; // backward
        if (!(raw & PAD_LEFT))  camera.pos.vx -= CAMERA_MOVE_SPEED; // strafe left
        if (!(raw & PAD_RIGHT)) camera.pos.vx += CAMERA_MOVE_SPEED; // strafe right

        if (!(raw & PAD_L1)) camera.pos.vy -= CAMERA_MOVE_SPEED; // up
        if (!(raw & PAD_R1)) camera.pos.vy += CAMERA_MOVE_SPEED; // down

        if (!(raw & PAD_SELECT)) camera.rot.vy -= CAMERA_ROT_SPEED; // yaw left
        if (!(raw & PAD_R2)) camera.rot.vy += CAMERA_ROT_SPEED;     // yaw right
        camera.rot.vy &= 4095;

        // Palette row nudge - edge-detected, wraps 0-15 (the per-TIM row
        // ceiling) rather than any one texture's real paletteCount,
        // since this is a single global nudge shared across every
        // placed object - draw_object_into_ot() clamps per-texture on
        // the output side, this is just input.
        if (!(raw & PAD_SQUARE) && (prevPadRaw & PAD_SQUARE))
            active_palette = (active_palette + 1) & 0x0F;

        if (!(raw & PAD_CIRCLE) && (prevPadRaw & PAD_CIRCLE))
            active_palette = (active_palette - 1) & 0x0F;
    }

    prevPadRaw = raw;
}


// Builds camera_view_matrix from camera.pos/camera.rot. Built exactly
// ONCE per frame; each placed object's own world matrix (below) is
// rebuilt per object that frame, composing against this same view matrix.
void update_camera_matrix(void)
{
    // ---- Camera's view matrix (inverse rotation + inverse translation) ----
    // RotMatrix(&camera.rot, ...) gives the camera's OWN orientation; the
    // view matrix needs the inverse (transpose, since rotation matrices
    // are orthonormal) so that rotating the camera one way appears to
    // rotate the world the other way, exactly like an FPS camera.
    MATRIX camera_rot_matrix;
    RotMatrix(&camera.rot, &camera_rot_matrix);

    camera_view_matrix.m[0][0] = camera_rot_matrix.m[0][0];
    camera_view_matrix.m[0][1] = camera_rot_matrix.m[1][0];
    camera_view_matrix.m[0][2] = camera_rot_matrix.m[2][0];
    camera_view_matrix.m[1][0] = camera_rot_matrix.m[0][1];
    camera_view_matrix.m[1][1] = camera_rot_matrix.m[1][1];
    camera_view_matrix.m[1][2] = camera_rot_matrix.m[2][1];
    camera_view_matrix.m[2][0] = camera_rot_matrix.m[0][2];
    camera_view_matrix.m[2][1] = camera_rot_matrix.m[1][2];
    camera_view_matrix.m[2][2] = camera_rot_matrix.m[2][2];

    // Translation part of the view matrix is the transposed rotation
    // applied to -camera.pos (rotate the negated eye position by the
    // inverse rotation, rather than negating camera.pos directly, so
    // translate and rotate stay consistent when both change in one
    // frame). CAMERA_DISTANCE is folded into camera.pos's initial value,
    // not a separate hardcoded push here.
    VECTOR neg_cam_pos = { -camera.pos.vx, -camera.pos.vy, -camera.pos.vz };
    camera_view_matrix.t[0] =
        ((camera_view_matrix.m[0][0] * neg_cam_pos.vx) +
         (camera_view_matrix.m[0][1] * neg_cam_pos.vy) +
         (camera_view_matrix.m[0][2] * neg_cam_pos.vz)) >> 12;
    camera_view_matrix.t[1] =
        ((camera_view_matrix.m[1][0] * neg_cam_pos.vx) +
         (camera_view_matrix.m[1][1] * neg_cam_pos.vy) +
         (camera_view_matrix.m[1][2] * neg_cam_pos.vz)) >> 12;
    camera_view_matrix.t[2] =
        ((camera_view_matrix.m[2][0] * neg_cam_pos.vx) +
         (camera_view_matrix.m[2][1] * neg_cam_pos.vy) +
         (camera_view_matrix.m[2][2] * neg_cam_pos.vz)) >> 12;

    // Live FOV: keeps the GTE's projection distance in sync with the fov
    // variable (changed via PAD_CROSS/PAD_CIRCLE). Frame-global, not
    // per-object, so this only needs to happen once per frame.
    gte_SetGeomScreen(FOCAL_LENGTH + fov);
}


// Builds world_matrix (rotation + per-axis scale + translation) for ONE
// placed object, composes it against camera_view_matrix into
// composed_matrix, and loads that into the GTE. Called once per resolved
// object per frame, before that object's cull check, normal rotation,
// and triangle draw.
void update_object_world_and_compose(const VECTOR *pos, SVECTOR *rot, const VECTOR *scale)
{
    // ---- Object's own world matrix (rotation + scale + translation) ----
    // RotMatrix() takes a non-const SVECTOR* (psxgte.h), so `rot` can't be
    // const here even though this function never writes through it.
    RotMatrix(rot, &world_matrix);

    // Apply per-axis scale by scaling each COLUMN of the rotation matrix
    // (R * diag(scale) - scaling before rotating equals scaling each
    // rotated basis column). scale->v{x,y,z} are 4096-scaled fixed point
    // (4096 == 1.0), matching RotMatrix()'s own m[][] scale; >>12 keeps
    // each product in that same fixed point.
    for (int row = 0; row < 3; row++)
    {
        world_matrix.m[row][0] = (world_matrix.m[row][0] * scale->vx) >> 12;
        world_matrix.m[row][1] = (world_matrix.m[row][1] * scale->vy) >> 12;
        world_matrix.m[row][2] = (world_matrix.m[row][2] * scale->vz) >> 12;
    }

    world_matrix.t[0] = pos->vx;
    world_matrix.t[1] = pos->vy;
    world_matrix.t[2] = pos->vz;

    // ---- Compose camera_view_matrix * world_matrix -> composed_matrix ----
    // Standard view*model composition, spelled out by hand:
    //   composed_rotation    = camera_rotation * object_rotation
    //   composed_translation = camera_rotation * object_translation + camera_translation
    // psxgte.h's CompMatrixLV() does this same job in one call and could
    // replace this block, but that's a deliberate follow-up rather than
    // applied here, since this hand-rolled version is proven correct and
    // working at 60fps.
    for (int row = 0; row < 3; row++)
    {
        for (int col = 0; col < 3; col++)
        {
            composed_matrix.m[row][col] =
                ((camera_view_matrix.m[row][0] * world_matrix.m[0][col]) +
                 (camera_view_matrix.m[row][1] * world_matrix.m[1][col]) +
                 (camera_view_matrix.m[row][2] * world_matrix.m[2][col])) >> 12;
        }
    }

    composed_matrix.t[0] =
        (((camera_view_matrix.m[0][0] * world_matrix.t[0]) +
          (camera_view_matrix.m[0][1] * world_matrix.t[1]) +
          (camera_view_matrix.m[0][2] * world_matrix.t[2])) >> 12) + camera_view_matrix.t[0];
    composed_matrix.t[1] =
        (((camera_view_matrix.m[1][0] * world_matrix.t[0]) +
          (camera_view_matrix.m[1][1] * world_matrix.t[1]) +
          (camera_view_matrix.m[1][2] * world_matrix.t[2])) >> 12) + camera_view_matrix.t[1];
    composed_matrix.t[2] =
        (((camera_view_matrix.m[2][0] * world_matrix.t[0]) +
          (camera_view_matrix.m[2][1] * world_matrix.t[1]) +
          (camera_view_matrix.m[2][2] * world_matrix.t[2])) >> 12) + camera_view_matrix.t[2];

    gte_SetRotMatrix(&composed_matrix);
    gte_SetTransMatrix(&composed_matrix);
}


// Rotates one model's face + vertex normals into the shared
// transformedNormals/transformedVertNormals scratch arrays, using
// whatever composed_matrix is CURRENTLY loaded in the GTE (i.e. must be
// called right after update_object_world_and_compose() for the same
// object, with nothing else touching the GTE's rotation matrix in
// between).
void rotate_object_normals(const MODEL_DEF *model)
{
    unsigned int triCount = model->triCount < MAX_MODEL_TRIS ? model->triCount : MAX_MODEL_TRIS;

    // SVECTOR normals don't need translation, so this writes into
    // transformedNormals using gte_rtv0 (rotate-only) rather than
    // gte_rtps (rotate+translate+project).
    for (unsigned int i = 0; i < triCount; i++)
    {
        gte_ldv0(&model->faceNormals[i]);
        gte_rtv0();
        gte_stsv(&transformedNormals[i]);
    }

    if (use_vertex_light)
    {
        unsigned int vertCount = model->vertCount < MAX_MODEL_VERTS ? model->vertCount : MAX_MODEL_VERTS;

        for (unsigned int i = 0; i < vertCount; i++)
        {
            gte_ldv0(&model->vertNormals[i]);
            gte_rtv0();
            gte_stsv(&transformedVertNormals[i]);
        }
    }
}


// Transforms every unique vertex of `model` through the GTE exactly ONCE
// (gte_ldv0 + gte_rtps, the single-vertex rotate+translate+perspective
// op), caching each result's screen XY and screen Z into
// transformedScreenXY[]/transformedScreenSZ[]. draw_object_into_ot()
// then looks these up per triangle corner instead of re-running a fresh
// gte_rtpt() (the triple/per-triangle version) for every triangle - most
// vertices are referenced by more than one triangle, so this is strictly
// less GTE work than the old per-triangle transform, scaling with
// vertCount instead of 3x triCount. Must be called after
// update_object_world_and_compose() for this same object (needs
// composed_matrix current), same ordering requirement as
// rotate_object_normals() above.
void transform_object_vertices(const MODEL_DEF *model)
{
    unsigned int vertCount = model->vertCount < MAX_MODEL_VERTS ? model->vertCount : MAX_MODEL_VERTS;

    for (unsigned int i = 0; i < vertCount; i++)
    {
        gte_ldv0(&model->verts[i]);
        gte_rtps();
        gte_stsxy(&transformedScreenXY[i]);
        gte_stsz(&transformedScreenSZ[i]);
    }
}


// Projects this model's bounding sphere (centre + two radius-offset edge
// points along model-space X/Y) through composed_matrix - which MUST
// already be current for this object (call right after
// update_object_world_and_compose() for the SAME object) - and rejects
// the object if it's entirely outside what would actually be drawn.
// Uses the GTE's real rotate+translate+perspective pipeline (gte_rtpt)
// rather than an approximate CPU formula, so culling can't disagree with
// what the real projection would have produced.
//
// Returns nonzero if the object should be skipped entirely.
int object_is_culled(const MODEL_DEF *model)
{
    // Two points offset from the bounding-sphere centre by its own
    // radius along model-space X and Y - bsphereCenter/bsphereRadius are
    // in the same fixed-point space as modelVerts, so this is a plain
    // integer add. Cast to short since SVECTOR fields are 16-bit; a
    // radius large enough to overflow that would already be pushing
    // modelVerts' own 16-bit range, so this isn't a new risk.
    SVECTOR edgeX = {
        (short)(model->bsphereCenter->vx + model->bsphereRadius),
        model->bsphereCenter->vy,
        model->bsphereCenter->vz
    };
    SVECTOR edgeY = {
        model->bsphereCenter->vx,
        (short)(model->bsphereCenter->vy + model->bsphereRadius),
        model->bsphereCenter->vz
    };

    gte_ldv3(model->bsphereCenter, &edgeX, &edgeY);
    gte_rtpt();

    // Same near-plane threshold draw_object_into_ot() uses per-triangle.
    // If ALL THREE points are behind/at the near plane, treat the object
    // as not visible. If only some are invalid (straddling the near
    // plane), fall through and still draw it - safer to render something
    // we're unsure about than to wrongly cull a partly-visible object.
    uint32_t sz0, sz1, sz2;
    gte_stsz3(&sz0, &sz1, &sz2);

    if (sz0 < 64 && sz1 < 64 && sz2 < 64)
        return 1;

    DVECTOR sxy[3];
    gte_stsxy3(&sxy[0], &sxy[1], &sxy[2]);

    // Approximate on-screen radius as the larger of the two edge points'
    // screen-space offset from centre (not exact under perspective, so a
    // flat safety margin is added). Deliberately conservative: under-
    // culling wastes a little work, over-culling is a visible bug.
    int screenRadiusX = sxy[1].vx - sxy[0].vx;
    if (screenRadiusX < 0) screenRadiusX = -screenRadiusX;

    int screenRadiusY = sxy[2].vy - sxy[0].vy;
    if (screenRadiusY < 0) screenRadiusY = -screenRadiusY;

    int screenRadius = (screenRadiusX > screenRadiusY) ? screenRadiusX : screenRadiusY;
    screenRadius += 8; // flat safety margin, pixels

    if (sxy[0].vx + screenRadius < 0 || sxy[0].vx - screenRadius > DISPLAY_W ||
        sxy[0].vy + screenRadius < 0 || sxy[0].vy - screenRadius > DISPLAY_H)
        return 1;

    return 0;
}


// Draws one model instance's triangles by inserting each one into the
// shared Ordering Table (ot[db]) instead of calling DrawPrim() directly -
// the GPU's own DrawOTag() walk (see main()) back-to-front sorts every
// object's triangles together, so objects need no depth-sort pass of
// their own. Positions are NOT re-transformed here - transform_object_
// vertices() must already have cached this object's screen-space verts
// (same ordering requirement as rotate_object_normals()); this function
// only culls/buckets/emits primitives from that cache.
void draw_object_into_ot(const MODEL_DEF *model, MODEL_TEXTURE **triTextureCache, unsigned int objectPalette)
{
    unsigned int triCount = model->triCount < MAX_MODEL_TRIS ? model->triCount : MAX_MODEL_TRIS;

    for (unsigned int i = 0; i < triCount; i++)
    {
        MODEL_TRI *tri = &model->tris[i];

        // Look up this triangle's 3 corners from the cache
        // transform_object_vertices() already filled for the whole
        // object, instead of re-running gte_ldv3+gte_rtpt per triangle.
        const DVECTOR *p0 = &transformedScreenXY[tri->v0];
        const DVECTOR *p1 = &transformedScreenXY[tri->v1];
        const DVECTOR *p2 = &transformedScreenXY[tri->v2];

        // Backface cull: the same cross-product winding test gte_nclip()
        // computes in hardware -
        //   MAC0 = SX0*SY1 + SX1*SY2 + SX2*SY0 - SX0*SY2 - SX1*SY0 - SX2*SY1
        // - done here on the CPU against the cached screen coords, since
        // these 3 vertices are no longer freshly loaded into the GTE
        // together. The reject sign (>= 0) is the same one verified
        // against the arrow.obj winding test in the coordinate-system
        // block above - unchanged, just relocated off the GTE.
        int32_t cross =
            (int32_t)p0->vx * p1->vy + (int32_t)p1->vx * p2->vy + (int32_t)p2->vx * p0->vy -
            (int32_t)p0->vx * p2->vy - (int32_t)p1->vx * p0->vy - (int32_t)p2->vx * p1->vy;

        if (cross >= 0)
            continue;

        DVECTOR sxy[3] = { *p0, *p1, *p2 };

        // Near-plane reject, same threshold as before - read from the
        // per-vertex SZ cache instead of a fresh gte_stsz3().
        uint32_t sz0 = transformedScreenSZ[tri->v0];
        uint32_t sz1 = transformedScreenSZ[tri->v1];
        uint32_t sz2 = transformedScreenSZ[tri->v2];

        if (sz0 < 64 || sz1 < 64 || sz2 < 64)
            continue;

        // gte_ldsz3 feeds these 3 cached SZ values back into the GTE's
        // own SZ pipeline registers (no re-transform needed), so
        // gte_avsz3/gte_stotz still produce the exact same hardware-
        // scaled OTZ this project's OT_Z_SHIFT was tuned against.
        int otz;
        gte_ldsz3(sz0, sz1, sz2);
        gte_avsz3();
        gte_stotz(&otz);

        int bucket = otz >> OT_Z_SHIFT;
        if (bucket < 0) bucket = 0;
        if (bucket > OT_LEN - 1) bucket = OT_LEN - 1;

        // Resolve this triangle's texture, if any, from the cache built
        // once in build_triangle_texture_cache() (not per-frame). Takes
        // the textured path only if the global preference is on AND this
        // triangle's material actually has a texture; otherwise falls
        // back to flat/Gouraud.
        MODEL_TEXTURE *tex = (triTextureCache != NULL) ? triTextureCache[i] : NULL;

        // Every primitive gets its own slot bump-allocated from
        // primBuffer[db] (see nextpri's comment), checked against
        // sizeof(POLY_FT3) - the largest of the three types - so this
        // check is correct no matter which branch below runs.
        if (primBytesRemaining < (long)sizeof(POLY_FT3))
        {
            primOverflowCount++;
            continue;
        }

        if (use_texture && tex != NULL)
        {
            // Textured path: samples model->uvs[] (byte-scaled 0-255 PS1
            // GPU coords) and binds this triangle's resolved texture's
            // TPAGE/CLUT (tex->tim, resolved once at load time).
            //
            // Uses flat (one-normal-per-triangle) brightness rather than
            // per-vertex Gouraud, keeping the textured path independent
            // of use_vertex_light. Textured+Gouraud (POLY_GT3) is a
            // possible future variant, not wired up here.
            POLY_FT3 *pol = (POLY_FT3 *)nextpri;
            setPolyFT3(pol);

            SVECTOR *n = &transformedNormals[i];

            int brightness = n->vz >> 2;
            if (brightness < 0)
                brightness = -brightness;
            if (brightness > 255)
                brightness = 255;
            brightness += 32;
            if (brightness > 255)
                brightness = 255;

            // RGB here MODULATES the texture's own sampled colour (GPU
            // multiplies texel colour by this RGB) rather than replacing
            // it - same brightness value as the flat path, just applied
            // as a tint instead of a literal fill colour.
            setRGB0(pol, brightness, brightness, brightness);

            setXY3(
                pol,
                sxy[0].vx, sxy[0].vy,
                sxy[1].vx, sxy[1].vy,
                sxy[2].vx, sxy[2].vy
            );

            // tri->uv0/uv1/uv2 index into model->uvs[][2] (converter-
            // emitted, split-vertex space - same index space as
            // tri->v0/v1/v2).
            setUV3(
                pol,
                model->uvs[tri->uv0][0], model->uvs[tri->uv0][1],
                model->uvs[tri->uv1][0], model->uvs[tri->uv1][1],
                model->uvs[tri->uv2][0], model->uvs[tri->uv2][1]
            );

            // TPAGE/CLUT resolved once at texture-load time (in
            // load_textures(), stored in tex->tim), not recomputed per-
            // triangle-per-frame - tex->tim.mode is the colour-depth bits
            // GetTimInfo() already decoded from that texture's TIM header.
            setTPage(pol, tex->tim.mode & 0x3, 0, tex->tim.prect->x, tex->tim.prect->y);

            // Multi-CLUT row select: tim.crect->y is row 0's VRAM Y; row
            // k lives at crect->y + k (one 16-texel, 1-pixel-tall strip
            // per row). objectPalette is this object's scene-authored
            // base row plus the live active_palette nudge, clamped
            // against THIS texture's own paletteCount.
            unsigned int row = objectPalette;
            if (tex->paletteCount == 0)
                row = 0; // shouldn't happen (converter enforces clut_height >= 1) but don't underflow below
            else if (row >= tex->paletteCount)
                row = tex->paletteCount - 1;

            setClut(pol, tex->tim.crect->x, tex->tim.crect->y + row);

            addPrim(&ot[db][bucket], pol);
            nextpri += sizeof(POLY_FT3);
            primBytesRemaining -= sizeof(POLY_FT3);
        }
        else if (use_vertex_light)
        {
            // Gouraud path: one brightness per vertex, looked up from
            // transformedVertNormals via this triangle's own vertex
            // indices (tri->v0/v1/v2 - same indices used to load
            // positions above). The GPU interpolates between these 3
            // colours across the triangle face in hardware.
            POLY_G3 *pol = (POLY_G3 *)nextpri;
            setPolyG3(pol);

            SVECTOR *nv0 = &transformedVertNormals[tri->v0];
            SVECTOR *nv1 = &transformedVertNormals[tri->v1];
            SVECTOR *nv2 = &transformedVertNormals[tri->v2];

            int b0 = nv0->vz >> 2;
            int b1 = nv1->vz >> 2;
            int b2 = nv2->vz >> 2;

            if (b0 < 0) b0 = -b0;
            if (b1 < 0) b1 = -b1;
            if (b2 < 0) b2 = -b2;

            b0 += 32; if (b0 > 255) b0 = 255;
            b1 += 32; if (b1 > 255) b1 = 255;
            b2 += 32; if (b2 > 255) b2 = 255;

            setRGB0(pol, b0, b0, b0);
            setRGB1(pol, b1, b1, b1);
            setRGB2(pol, b2, b2, b2);

            setXY3(
                pol,
                sxy[0].vx, sxy[0].vy,
                sxy[1].vx, sxy[1].vy,
                sxy[2].vx, sxy[2].vy
            );

            addPrim(&ot[db][bucket], pol);
            nextpri += sizeof(POLY_G3);
            primBytesRemaining -= sizeof(POLY_G3);
        }
        else
        {
            // Flat path: one colour per triangle, from the precomputed,
            // GTE-rotated face normal built in rotate_object_normals().
            POLY_F3 *pol = (POLY_F3 *)nextpri;
            setPolyF3(pol);

            SVECTOR *n = &transformedNormals[i];

            int brightness = n->vz >> 2;
            if (brightness < 0)
                brightness = -brightness;
            if (brightness > 255)
                brightness = 255;
            brightness += 32;
            if (brightness > 255)
                brightness = 255;

            setRGB0(pol, brightness, brightness, brightness);

            setXY3(
                pol,
                sxy[0].vx, sxy[0].vy,
                sxy[1].vx, sxy[1].vy,
                sxy[2].vx, sxy[2].vy
            );

            addPrim(&ot[db][bucket], pol);
            nextpri += sizeof(POLY_F3);
            primBytesRemaining -= sizeof(POLY_F3);
        }
    }
}


// Resolves the ACTUAL per-frame pos/rot/scale for scene object `i` of
// the active scene: that object's own scene-authored transform, plus the
// global debug offset/multiplier (model_pos/model_rot/debug_scale) - see
// those variables' own comments.
static void get_object_transform(const SCENE_OBJECT *obj, VECTOR *outPos, SVECTOR *outRot, VECTOR *outScale)
{
    outPos->vx = obj->pos.vx + model_pos.vx;
    outPos->vy = obj->pos.vy + model_pos.vy;
    outPos->vz = obj->pos.vz + model_pos.vz;

    outRot->vx = (obj->rot.vx + model_rot.vx) & 4095;
    outRot->vy = (obj->rot.vy + model_rot.vy) & 4095;
    outRot->vz = (obj->rot.vz + model_rot.vz) & 4095;

    // Both obj->scale and debug_scale are 4096-scaled fixed point; combine
    // them with a fixed-point multiply (>>12) rather than just adding, so
    // debug_scale acts as a MULTIPLIER on top of each object's own scale
    // (e.g. debug_scale==8192 doubles whatever every object already had),
    // not an independent additive offset.
    outScale->vx = (obj->scale.vx * debug_scale) >> 12;
    outScale->vy = (obj->scale.vy * debug_scale) >> 12;
    outScale->vz = (obj->scale.vz * debug_scale) >> 12;
}


// Resolves and draws every placed object in the active scene into the
// shared OT (ot[db], reset by main() before this is called each frame).
//
// No object-level depth sort: draw_object_into_ot() inserts every
// triangle into ONE shared OT keyed by its own depth bucket, so the
// GPU's DrawOTag() walk (see main()) sorts every triangle from every
// object together - objects can be processed in any order. Per object:
// resolve its model (done once at scene load), build its matrix,
// frustum-cull it, and if visible, light + draw it.
void draw_scene(void)
{
    visibleObjectCount = 0;
    culledObjectCount = 0;

    if (activeSceneIndex >= sceneRegistryCount)
        return;

    const SCENE_DEF *scene = &sceneRegistry[activeSceneIndex];
    unsigned int objectCount = activeSceneObjectCount;

    for (unsigned int i = 0; i < objectCount; i++)
    {
        int modelIndex = sceneObjectModelIndex[i];
        if (modelIndex < 0)
        {
            // Unresolved model name (e.g. scene references "garage" but
            // assets/garage/garage.obj doesn't exist yet) - already
            // counted in sceneUnresolvedCount at scene-load time; not
            // double-counted as "culled" here.
            continue;
        }

        const MODEL_DEF *model = &modelRegistry[modelIndex];
        const SCENE_OBJECT *obj = &scene->objects[i];

        VECTOR objPos, objScale;
        SVECTOR objRot;
        get_object_transform(obj, &objPos, &objRot, &objScale);

        update_object_world_and_compose(&objPos, &objRot, &objScale);

        if (object_is_culled(model))
        {
            culledObjectCount++;
            continue;
        }

        visibleObjectCount++;

        rotate_object_normals(model);
        transform_object_vertices(model);

        MODEL_TEXTURE **triTextureCache = modelTriTextureCache[modelIndex];
        unsigned int objectPalette = obj->palette + active_palette;

        draw_object_into_ot(model, triTextureCache, objectPalette);
    }
}


// Print debug text to the screen
void debug_text(int counter)
{
    FntPrint(-1, "OBJ MODEL TEST (GTE)\n");
    FntPrint(-1, "FRAME=%d\n", counter);

    FntPrint(-1, "SCENE=%s OBJECTS=%d/%d UNRESOLVED=%d\n",
        (activeSceneIndex < sceneRegistryCount) ? sceneRegistry[activeSceneIndex].name : "(none)",
        activeSceneObjectCount,
        (activeSceneIndex < sceneRegistryCount) ? sceneRegistry[activeSceneIndex].objectCount : 0,
        sceneUnresolvedCount);
    FntPrint(-1, "VISIBLE=%d CULLED=%d PRIM_OVERFLOW=%d\n",
        visibleObjectCount, culledObjectCount, primOverflowCount);
    FntPrint(-1, "MODELS_BAKED=%d\n", modelRegistryCount);

    FntPrint(-1, "DEBUGSCALE=%d\n", debug_scale);
    // NOTE: this prints FOCAL_LENGTH+fov as if it's the live projection
    // distance, but see the comment above update() - fov currently isn't
    // fed back into gte_SetGeomScreen(), so this number moves while the
    // actual FOV does not. Either wire fov into the GTE each frame or
    // drop it from this readout until that's done.
    FntPrint(-1, "FOV=%d\n", FOCAL_LENGTH+fov);
    FntPrint(-1, "ROTX=%d\n", model_rot.vx);
    FntPrint(-1, "ROTY=%d\n", model_rot.vy);
    FntPrint(-1, "ROTZ=%d\n", model_rot.vz);
    FntPrint(-1, "DEBUGPOSOFFSET=%d,%d,%d\n", model_pos.vx, model_pos.vy, model_pos.vz);
    FntPrint(-1, "CAMPOS=%d,%d,%d\n", camera.pos.vx, camera.pos.vy, camera.pos.vz);
    FntPrint(-1, "CAMROTY=%d\n", camera.rot.vy);
    FntPrint(-1, "VERTEXLIGHTING=%d\n", use_vertex_light);
    FntPrint(-1, "TEXTURED=%d\n", use_texture);
    FntPrint(-1, "TEXTURES_LOADED=%d\n", textureTableCount);
    FntPrint(-1, "ACTIVE_PALETTE=%d\n", active_palette);
    FntPrint(-1, "SCHEMA=%s (hold L2 for CAMERA)\n", cameraSchemaActive ? "CAMERA" : "DEBUG");
}


// Main function, program entrypoint
int main(int argc, const char *argv[])
{
    int counter = 0;

    init();

    while (1)
    {
        update();

        // Camera-only matrix rebuild - once per frame, shared by every
        // object draw_scene() composes against this frame.
        update_camera_matrix();

        // Reset THIS frame's OT (ClearOTagR wires every bucket to link
        // to the next, all initially empty) and rewind the primitive
        // bump allocator - both keyed by the CURRENT db, matching
        // whichever draw environment display() left active last call.
        ClearOTagR(ot[db], OT_LEN);
        nextpri = primBuffer[db];
        primBytesRemaining = (long)sizeof(primBuffer[db]);
        primOverflowCount = 0;

        // Resolve, frustum-cull, and draw every placed object in the
        // active scene into ot[db] - replaces the old single-model
        // update_matrix()+sort_model()+draw_model() trio, and no longer
        // does its own CPU depth sort (the OT does that instead).
        draw_scene();

        // Kick off the GPU's own back-to-front walk of everything
        // draw_scene() just queued into ot[db], starting from the
        // FARTHEST bucket (OT_LEN - 1) - this call itself is
        // non-blocking (just enqueues the GPU command), the actual wait
        // for it to finish happens in display()'s DrawSync(0) below.
        DrawOTag(ot[db] + (OT_LEN - 1));

        debug_text(counter);

        // Draw text LAST so it paints on top of every object's
        // primitives instead of being drawn first and then covered by
        // them - text and the OT triangles both just append to the same
        // GPU command sequence for this frame, so whatever's issued last
        // ends up on top.
        FntFlush(-1);

        display();

        counter++;
    }

    return 0;
}
