// root/main.c

/*
 * PSn00bSDK - OBJ Model Renderer (GTE version)
 *
 * Current features:
 * - Filled triangle rendering
 * - OBJ importer support
 * - Runtime scaling (debug_scale, a live fixed-point multiplier layered
 *   over every stage object's own authored scale - see draw_stage())
 * - XYZ rotation (GTE-driven)
 * - GTE perspective projection
 * - Backface culling (same winding test gte_nclip computes in hardware,
 *   done in software against cached screen coords - see the per-vertex
 *   transform caching bullet below)
 * - GTE-rotated face normals for flat lighting
 * - GTE-rotated vertex normals for Gouraud lighting
 * - Textured polygon rendering (POLY_FT3)
 * - Multi-CLUT palette-swap textures (stacked CLUT rows in one TIM,
 *   base row is per-object stage data, live-nudged via SQUARE/CIRCLE in
 *   the camera control schema - hold L2, see update())
 * - GPU Ordering Table (OT_LEN buckets - see draw_object_into_ot()):
 *   every triangle from every visible object is inserted into ONE shared
 *   OT keyed by its own gte_avsz3()-derived depth bucket; the GPU's
 *   linked-list walk (DrawOTag()) does the back-to-front sort, replacing
 *   the old CPU insertion sort entirely
 * - Per-vertex transform caching (transform_object_vertices()): each
 *   unique model vertex is rotated/translated/projected through the GTE
 *   exactly ONCE per object per frame (gte_rtps), cached, and looked up
 *   per triangle corner - instead of re-running the GTE's triple
 *   transform (gte_rtpt) for every triangle a vertex appears in
 * - Per-object frustum culling (object_is_culled()): projects each
 *   object's own bounding sphere (centre + two radius-offset edge
 *   points) through its real composed matrix and rejects it before
 *   touching any of its triangles if it's behind the near plane or
 *   entirely outside the 320x240 screen bounds
 * - Stage loading (assets/stage/*_/stage.json -> generated/stage_*.c): places
 *   named model instances with their own pos/rot/scale/palette
 * - Multiple simultaneous models (generated/model_registry.c), resolved
 *   by name per stage object instead of one hand-#include'd model
 * - Double buffering
 * - Single-controller input (see update()): holding L2 switches pad 1
 *   from the debug transform schema to the camera schema
 *
 */

// Toolchain paths (set these as env vars on your machine, not hardcoded
// here - PATH, PSN00BPS1_TOOLS, PSN00BSDK_LIBS). See py_convert_assets.py,
// py_convert_textures.py and py_convert_stages.py for the asset-side
// equivalents.

#include <stdio.h>
#include <string.h>
#include <sys/types.h>

#include <psxetc.h>
#include <psxgte.h>
#include <psxgpu.h>
#include <psxapi.h>   // BIOS API: InitPAD, StartPAD, ChangeClearPAD, etc.
#include <psxpad.h>   // PadButton enums (PAD_UP, PAD_DOWN, PAD_LEFT, PAD_RIGHT)
#include <inline_c.h> // GTE macros (gte_ldv0, gte_rtpt, gte_nclip, etc.)

// SPU core (sound.c): boots SPU + CD and owns the shared SPU RAM allocator.
// sound_init() must run after ResetGraph()/InitGeom() (see init()). Playback
// lives in sfx.c (stage-authored looping ambients, loaded per stage by
// load_stage(); START toggles the ambience - see update()) and music.c.
#include "sound.h"
#include "sfx.h"
#include "music.h"


// Every discovered assets/object/<name>/<name>.obj, baked in unconditionally.
// Defines MODEL_TRI/MODEL_DEF (via model_common.h), each <name>_model*
// array, and modelRegistry[]/modelRegistryCount. See py_convert_assets.py.
#include "generated/models_all.h"

// Concatenated texture blob (all TIMs back-to-back) + offset/length table,
// both generated by py_convert_textures.py. tex_blob_start is the base
// pointer every texBlobMaterialTable offset is relative to. TEX_BLOB_ENTRY
// and the tex_blob_start/end + texBlobMaterialTable externs live in
// generated/tex_blob_table.h, shared by tex_blob_table.c and main.c.
#include "generated/tex_blob_table.h"

// Every discovered assets/stage/*/stage.json, baked in unconditionally. Defines
// STAGE_OBJECT/STAGE_DEF (via stage_common.h), each stage's own
// <name>_objects[]/<name>_objectCount, and stageRegistry[]/
// stageRegistryCount. See py_convert_stages.py. Stage objects resolve
// model NAMES against modelRegistry[] at RUNTIME (load_stage(), below),
// not at compile time, so there's no real build-order dependency on
// models_all.h above.
#include "generated/stages_all.h"

// Runtime texture table - one resolved TIM_IMAGE per material name found
// in the blob, built once in load_textures() by walking
// texBlobMaterialTable and calling GetTimInfo() on each blob slice. Fixed
// size (no heap on PS1); bump MAX_TEXTURES if this ceiling is ever hit.
#define MAX_TEXTURES 32

typedef struct
{
    const char *material;
    TIM_IMAGE tim;
    uint8_t loaded;

    // Stacked CLUT row count (1 for a plain single-palette texture).
    // draw_object_into_ot() clamps a placed object's palette row against
    // this before adding it to tim.crect->y, so an out-of-range row can't
    // read into another texture's VRAM data.
    unsigned int paletteCount;
} MODEL_TEXTURE;

static MODEL_TEXTURE textureTable[MAX_TEXTURES];
static unsigned int textureTableCount = 0;

// Per-model material name table (modelRegistry[].materialNames/
// materialCount, emitted by py_convert_assets.py from each .obj's usemtl
// lines). tri->material indexes THAT model's own materialNames;
// build_triangle_texture_cache() resolves that name against
// textureTable[] to find the actual TIM_IMAGE, if any - this indirection
// is what lets material index 0 mean different textures per model.



// Screen consts (for model placement)
#define DISPLAY_W 320
#define DISPLAY_H 240

#define SCREEN_CX (DISPLAY_W / 2)
#define SCREEN_CY (DISPLAY_H / 2)



// ============================================================
// COORDINATE SYSTEM - FINALISED (v4, verified via arrow.obj dual-tip test)
// ============================================================
// Source assets are authored in Blender, exported with Forward=-Z, Up=Y.
// The converter (py_convert_assets.py, get_split_vertex()) remaps every
// vertex/normal at export time so that:
//
//   renderer_X =  Blender_X
//   renderer_Y = -Blender_Z
//   renderer_Z = -Blender_Y
//
// Verified with a two-tipped arrow test object: Blender's +Y tip renders
// pointing AWAY from the camera; Blender's +Z tip renders pointing UP on
// screen. A model's Blender-up is screen-up, and its Blender-forward
// (+Y) points away from the camera by default with model_rot = {0,0,0} -
// no per-model rotation offset needed.
//
// Winding/cull sign (draw_object_into_ot()'s gte_nclip/cross check) was
// re-verified against this final mapping: front-facing triangles are
// correctly kept with `if (cross >= 0) continue;` as the reject
// condition. If this coordinate block changes again, re-check that sign
// against the arrow.obj test - it flips whenever an even number of axes
// change sign, and stays put when an odd number do (a mnemonic, not a
// substitute for testing).
//
// Do NOT re-flip or re-derive axes anywhere else in this file. If a
// specific model renders mirrored or backwards, re-test with arrow.obj
// first - the bug is very likely elsewhere (a bad per-model rotation
// default, or that one asset having different OBJ export settings), not
// this coordinate system.
#define CAMERA_DISTANCE 4096
#define FOCAL_LENGTH    256
int fov = FOCAL_LENGTH;
int fov_speed = 10;

// Maximum number of vertices we cache for a transformed model.
// Bumped from 127 -> 512 for Option B vertex-splitting at seams: a split
// model's vertex count can exceed its raw OBJ 'v' count (each hard-edge
// seam duplicates a position per distinct normal/UV it's used with). Check
// the converter's printed "Split vertex count" against this on each
// model swap - if a model ever exceeds 512, bump this again.
#define MAX_MODEL_VERTS 512

// Maximum number of triangles we cache for sorting/lighting, PER MODEL.
// (Raised from the original 256 alongside the MAX_MODEL_VERTS bump above;
// py_convert_assets.py's MAX_MATERIALS_PER_MODEL note tracks this value.)
#define MAX_MODEL_TRIS 512

// Ceiling on how many distinct models (modelRegistry[] entries) get their
// own triangle/texture cache built at load time - see
// build_triangle_texture_cache(). Bump if assets/object/ grows past this many
// distinct model folders; modelRegistryCount is clamped against it
// rather than trusted blindly, same fail-safe pattern as MAX_TEXTURES.
#define MAX_MODELS 16

// Ceiling on how many objects a single stage can place at once (fixed-
// size arrays, no heap on PS1). Bump if a stage needs more; stage
// object counts are clamped against this in load_stage(), same pattern
// as MAX_MODELS/MAX_TEXTURES.
#define MAX_STAGE_OBJECTS 32

// ------------------------------------------------------------
// GPU Ordering Table
// ------------------------------------------------------------
// Number of depth buckets in the OT. Each bucket holds a linked list of
// primitives at roughly that depth; DrawOTag() walks every bucket
// farthest-to-nearest in hardware - this is what sorts the frame (see
// draw_object_into_ot()). More buckets = finer back-to-front resolution
// at the cost of a bigger ClearOTagR() per frame and more static RAM;
// bump if far-apart triangles start visibly fighting.
#define OT_LEN 1024

// Right-shift applied to the raw gte_avsz3()/gte_stotz() depth value
// before clamping it into an OT bucket index. Per inline_c.h, gte_avsz3()
// computes OTZ = ZSF3*(SZ1+SZ2+SZ3)/4096 - ZSF3 itself is set by
// InitGeom() (not exposed as a header macro, so its default isn't
// visible here), so the exact numeric range OTZ lands in for this
// project's camera/model scale is still empirical. TUNE THIS: raise the
// shift if distant geometry clumps into the last bucket; lower it if
// nearby triangles land in too few buckets.
#define OT_Z_SHIFT 2

// Upper bound on triangles insertable into the OT in a single frame,
// across every visible object. primBytesRemaining enforces this as a
// hard runtime cap - an over-budget stage drops triangles (reported via
// debug_text()'s PRIM_OVERFLOW counter) instead of overrunning the
// primitive arena.
#define MAX_PRIMS_PER_FRAME 4096



// Double buffering
// Define display/draw environments for double buffering
DISPENV disp[2];
DRAWENV draw[2];
int db;

// The Ordering Table itself, double-buffered like disp/draw so the GPU
// can still be walking last frame's OT (DrawOTag()) while the CPU fills
// the OTHER buffer's OT for the next frame.
static uint32_t ot[2][OT_LEN];

// Primitive packet storage backing the OT above. ClearOTagR()/addPrim()
// only manage the ot[] linked-list structure - the actual POLY_F3/POLY_G3/
// POLY_FT3 data has to live somewhere that survives until DrawOTag()
// finishes walking it, so every triangle gets its OWN slot, bump-
// allocated from this arena via nextpri/primBytesRemaining below. Sized
// as MAX_PRIMS_PER_FRAME worst-case POLY_FT3s (the largest of the three
// types); the bump allocator advances by each primitive's real size, so
// the byte budget is correct regardless of the actual type mix.
static char primBuffer[2][MAX_PRIMS_PER_FRAME * sizeof(POLY_FT3)];

// Bump-allocator cursor into primBuffer[db] - reset at the top of every
// main() loop iteration, advanced by sizeof(<primitive type>) each time
// draw_object_into_ot() allocates one.
static char *nextpri;

// Remaining bytes in primBuffer[db] this frame - checked against
// sizeof(POLY_FT3) (the largest type) before every allocation so an
// over-budget stage drops triangles instead of overrunning the arena.
static long primBytesRemaining;

// Debug counters, reset once per frame in draw_stage()/main() - see
// debug_text().
static unsigned int visibleObjectCount = 0;
static unsigned int culledObjectCount = 0;
static unsigned int primOverflowCount = 0;



// Gamepad buffers (BIOS pad driver style)
static unsigned char padbuf[2][34];

// Previous frame's raw pad state, used for edge detection on toggle
// buttons (TRIANGLE/SQUARE) so a held button doesn't re-toggle every
// single frame (60x/sec) - only the released->pressed transition fires.
unsigned short prevPadRaw = 0xFFFF; // all-released, matches BIOS idle state

// Latched control mode, cycled by the SELECT click (edge-detected in
// update()). Replaces the old hold-L2/hold-R2 modifier schemas: nothing is
// held any more, so each mode owns the whole pad. PLAY is the boot default
// (the actual game); CAMERA and DEBUG are dev tooling you tab into. Cycle
// order is PLAY -> CAMERA -> DEBUG -> PLAY. debug_text() reads control_mode
// to show the active mode on screen.
enum { MODE_PLAY = 0, MODE_CAMERA, MODE_DEBUG, MODE_COUNT };
static int control_mode = MODE_PLAY;

// Which debug overlay page is shown, cycled by the L3 click (edge-detected
// in update(); requires the DualShock in analog mode). debug_text() reads
// this to pick which block of readouts to print.
static int debug_page = 0;
#define DEBUG_PAGE_COUNT 1



// ------------------------------------------------------------
// Camera
// ------------------------------------------------------------
// The GTE only transforms vertices relative to a fixed origin, so
// "moving the camera" means translating/rotating vertices by the inverse
// of the camera's transform - accumulated in one shared CAMERA struct
// (independent of any model's own transform) so multiple placed models
// can share one camera and camera movement only touches this struct.
typedef struct
{
    VECTOR  pos;   // world-space position
    SVECTOR rot;   // 12-bit fixed-point angles (4096 = 360 degrees), same format as model_rot
} CAMERA;

// Compiled-in fallback if stageRegistryCount is ever 0 (e.g. assets/stage/ is
// empty) - load_stage() overwrites this from the active stage's own
// "camera" block otherwise.
CAMERA camera = { { 0, 0, -CAMERA_DISTANCE }, { 0, 0, 0 } };

const int32_t CAMERA_MOVE_SPEED = 32;   // world units per frame, same fixed-point scale as modelVerts
const uint16_t CAMERA_ROT_SPEED = 22;   // matches ROT_SPEED below for consistency

// Camera's own view matrix - rotation + translation for -camera.pos,
// rebuilt once per frame in update_camera_matrix(). Composed with each
// placed object's own world matrix in update_object_world_and_compose()
// rather than fed to the GTE directly.
MATRIX camera_view_matrix;

// Composed matrix (camera_view_matrix * world_matrix) actually fed to the
// GTE each frame - kept separate from world_matrix so world_matrix always
// represents only the CURRENT object's own transform (reused as scratch
// across however many objects the stage places, one at a time).
MATRIX composed_matrix;



// ------------------------------------------------------------
// Player (third-person schema, R2 held). NOT a stage-authored object -
// summoned at runtime the first time the R2 schema is entered, drawn by
// draw_player() through the same compose/cull/draw pipeline as stage
// objects. Confined to a flat plane (XZ) with NO gravity - vy is pinned
// to PLAYER_GROUND_Y every frame - and followed by an orbiting
// third-person camera (update_player_follow_camera()).
// ------------------------------------------------------------
static int playerModelIndex = -1;         // resolved from "player" in init(); -1 = not baked yet
static int playerSpawned = 0;             // set once the R2 schema summons it
static VECTOR player_pos = { 0, 0, 0 };   // world-space; vy re-pinned to ground each frame
static SVECTOR player_rot = { 0, 0, 0 };  // faces the direction of travel (see update())
static int player_cam_yaw = 0;            // 12-bit follow-cam yaw, orbited via L1/R1 in PLAY
static int player_cam_pitch = 128;        // follow-cam view pitch, nudged by L2/R2 in PLAY

#define PLAYER_GROUND_Y     0             // the flat plane the player is confined to (no gravity)
#define PLAYER_MOVE_SPEED   28            // world units/frame at full D-pad deflection
#define PLAYER_CAM_DIST     2200          // how far BEHIND the player the follow-cam sits
#define PLAYER_CAM_HEIGHT   900           // how far ABOVE the player the follow-cam sits
#define PLAYER_CAM_YAW_SPEED 22           // follow-cam yaw units/frame while L1/R1 held (orbit)
#define PLAYER_CAM_PITCH_SPEED 12         // follow-cam pitch units/frame while L2/R2 held
#define PLAYER_CAM_PITCH_MIN (-300)       // clamp so the view can't flip past straight up
#define PLAYER_CAM_PITCH_MAX 700          // clamp so the view can't flip past straight down


// 12-bit fixed-point atan2 (returns 0..4095, the engine's angle format;
// 0 = +forward, increasing clockwise when used as a yaw). psxgte.h ships
// isin/icos but no inverse, so this uses the classic octant-folded
// approximation a ~ 1024*y/(x+y) - worst-case error under ~4 degrees,
// plenty for pointing a character model down its travel direction.
static int fp_atan2(int y, int x)
{
    if (x == 0 && y == 0)
        return 0;

    int ax = x < 0 ? -x : x;
    int ay = y < 0 ? -y : y;
    int a;

    if (ax >= ay)
        a = (ay * 1024) / (ax + ay);            // 0..512 within the octant
    else
        a = 1024 - (ax * 1024) / (ax + ay);     // fold across the 45-degree line

    if (x < 0) a = 2048 - a;                    // fold across the Y axis
    if (y < 0) a = -a;                          // fold across the X axis

    return a & 4095;
}



// ------------------------------------------------------------
// Debug transform - a global offset/multiplier layered on top of EVERY
// stage object's own authored pos/rot/scale (see draw_stage()), driven
// by pad 1. Purely a live testing knob - e.g. spin the whole stage to
// eyeball lighting, or nudge every object at once without reconverting.
// ------------------------------------------------------------
int debug_scale = 4096;                 // fixed-point multiplier, 4096 == 1.0x
const uint16_t SCALE_SPEED = 64;        // ~1.5% of 1.0x per frame
const uint8_t ROT_SPEED = 22;

// XYZ rotation angles, fed straight into RotMatrix() as an SVECTOR.
// 12-bit fixed-point angle format (4096 = 360 degrees).
SVECTOR model_rot = { 0, 0, 0 };

// Debug world-position OFFSET, added to every stage object's own pos.
// Zero by default (no pad control wired to it today).
VECTOR model_pos = { 0, 0, 0 };

// GTE rotation matrix, rebuilt once per object per frame in
// update_object_world_and_compose(). Represents ONLY that object's own
// transform - the camera is composed in separately (already built in
// update_camera_matrix()).
MATRIX world_matrix;

// Rotated face normal cache (one per triangle, post-transform), reused
// as shared scratch across every drawn object - draw_stage() always
// fully finishes one object (rotate -> cull -> draw) before moving to
// the next, so nothing here needs to survive past a single object's turn.
// Index-matches a model's faceNormals/tris 1:1.
SVECTOR transformedNormals[MAX_MODEL_TRIS];

// Rotated VERTEX normal cache, same shared-scratch reasoning as
// transformedNormals above. Index-matches vertNormals/verts 1:1; looked
// up per-triangle-corner in draw_object_into_ot() for Gouraud shading.
SVECTOR transformedVertNormals[MAX_MODEL_VERTS];

// Cached per-vertex screen-space projection, one entry per unique model
// vertex - built ONCE per object per frame by transform_object_vertices()
// (gte_ldv0 + gte_rtps, the single-vertex transform), then looked up per
// triangle CORNER in draw_object_into_ot() instead of re-running a fresh
// gte_rtpt() per TRIANGLE. Since most vertices are shared by more than
// one triangle, this cuts the GTE's most expensive op (rotate+translate+
// perspective) from 3x triangleCount down to just vertCount calls per
// object. Same shared-scratch reasoning as transformedNormals above.
static DVECTOR transformedScreenXY[MAX_MODEL_VERTS];
static uint32_t transformedScreenSZ[MAX_MODEL_VERTS];

// Per-model (not per-instance) triangle -> texture lookup cache, indexed
// [modelRegistry index][triangle index]. Filled once at startup (not
// per-frame) by build_triangle_texture_cache(): resolves
// materialNames[tri->material] against textureTable[] by name, or NULL
// if that material has no texture (flat-colour materials fall back to
// flat/Gouraud instead of forcing POLY_FT3).
static MODEL_TEXTURE *modelTriTextureCache[MAX_MODELS][MAX_MODEL_TRIS];

// Which baked stage (stageRegistry[]) is currently active. 0 = first
// discovered assets/stage/*/stage.json (alphabetical, see py_convert_stages.py).
// Nothing in the render path assumes a fixed stage index, so a future
// runtime stage switch just needs to change this.
unsigned int activeStageIndex = 0;

// Set by load_stage(): how many of stageRegistry[activeStageIndex]'s
// objects actually get drawn (its objectCount, clamped to MAX_STAGE_OBJECTS).
static unsigned int activeStageObjectCount = 0;

// Set by load_stage(): stageObjectModelIndex[i] is the modelRegistry[]
// index the i'th stage object's "model" name resolved to, or -1 if no
// such model exists (e.g. a typo'd or not-yet-created name) - resolved
// ONCE at stage load, not per-frame; draw_stage() skips unresolved
// objects instead of dereferencing NULL.
static int stageObjectModelIndex[MAX_STAGE_OBJECTS];

// Set by load_stage(): count of objects whose model name didn't
// resolve, surfaced via debug_text()'s UNRESOLVED readout.
static unsigned int stageUnresolvedCount = 0;



void load_textures(void)
{
    // Parses the concatenated blob (tex_blob_start[], via tex_blob.S's
    // .incbin) using the offset table py_convert_textures.py generated
    // (texBlobMaterialTable[]/texBlobEntryCount). Each entry's
    // offset/length slices out one standalone TIM's bytes; GetTimInfo()
    // parses that slice exactly as it would a standalone .tim file.
    textureTableCount = 0;

    for (unsigned int i = 0; i < texBlobEntryCount && textureTableCount < MAX_TEXTURES; i++)
    {
        const TEX_BLOB_ENTRY *entry = &texBlobMaterialTable[i];

        MODEL_TEXTURE *slot = &textureTable[textureTableCount];
        slot->material = entry->material;
        slot->paletteCount = entry->paletteCount;

        const unsigned char *tim_bytes = tex_blob_start + entry->offset;

        // GetTimInfo() expects a const uint32_t* - the blob is just raw
        // bytes, so this cast doesn't change layout, only how the pointer
        // is typed for the SDK call (same reasoning as the old single-
        // texture face_tim_start[] declaration).
        GetTimInfo((const uint32_t *)tim_bytes, &slot->tim);

        // Upload pixel data to VRAM at the rect the TIM specifies.
        LoadImage(slot->tim.prect, slot->tim.paddr);

        // Upload CLUT data to VRAM ONE ROW AT A TIME rather than as a
        // single N-row block. 4-bit TIMs always carry a CLUT (16 colours);
        // this would be skipped for a 24-bit direct-colour TIM, but we're
        // 4-bit here so crect/caddr are always set for every entry in
        // this blob.
        //
        // A single LoadImage() covering all N rows at once hangs on
        // DuckStation (confirmed by bisection - never reproduced with a
        // single-row CLUT, which is all every texture before multi-CLUT
        // support ever had). Root cause not confirmed, suspected to be an
        // untested DMA block-chunking path in the SDK's _dma_transfer()
        // (libpsn00b/psxgpu/image.c). Splitting into N single-row (16x1)
        // transfers keeps every call on the same shape that already works
        // - if this reproduces on real hardware too, worth reporting
        // upstream to PSn00bSDK.
        if (slot->tim.crect != 0)
        {
            RECT clutRow = *slot->tim.crect;
            clutRow.h = 1;

            for (unsigned int row = 0; row < (unsigned int) slot->tim.crect->h; row++)
            {
                clutRow.y = slot->tim.crect->y + row;

                // caddr is a uint32_t* (2 packed 16-bit colours per word);
                // each 16-colour row is 32 bytes = 8 words, so row k's
                // data starts 8*k words into caddr.
                LoadImage(&clutRow, slot->tim.caddr + (row * 8));
            }
        }

        slot->loaded = 1;
        textureTableCount++;
    }

    // Make sure every upload above has actually landed in VRAM before any
    // draw call tries to sample from them.
    DrawSync(0);
}


// Look up a texture by material name (linear scan - textureTableCount is
// small, typically single digits to low tens, so this is fine to do once
// per triangle at model-load time; see build_triangle_texture_cache()).
static MODEL_TEXTURE *find_texture_by_material(const char *material_name)
{
    for (unsigned int i = 0; i < textureTableCount; i++)
    {
        if (strcmp(textureTable[i].material, material_name) == 0)
            return &textureTable[i];
    }
    return NULL;
}


// Resolves every triangle's material index (into that model's own
// materialNames[]) to an actual texture pointer, once at load time, for
// every model in modelRegistry[]. Triangles whose material has no
// matching textureTable[] entry get NULL, which draw_object_into_ot()
// treats as "use flat/Gouraud shading" instead of a textured path.
void build_triangle_texture_cache(void)
{
    unsigned int modelCount = modelRegistryCount < MAX_MODELS ? modelRegistryCount : MAX_MODELS;

    for (unsigned int m = 0; m < modelCount; m++)
    {
        const MODEL_DEF *model = &modelRegistry[m];
        unsigned int triCount = model->triCount < MAX_MODEL_TRIS ? model->triCount : MAX_MODEL_TRIS;

        for (unsigned int i = 0; i < triCount; i++)
        {
            unsigned char material_index = model->tris[i].material;

            if (material_index >= model->materialCount)
            {
                // Shouldn't happen if py_convert_assets.py and this file
                // agree on MAX_MATERIALS_PER_MODEL, but fail safe to "no
                // texture" rather than reading out of bounds.
                modelTriTextureCache[m][i] = NULL;
                continue;
            }

            const char *material_name = model->materialNames[material_index];
            modelTriTextureCache[m][i] = find_texture_by_material(material_name);
        }
    }
}


// Linear scan over modelRegistry[] by name (small table, fine to do once
// per stage object at stage load). Returns -1 if no model with that name
// was baked in.
static int find_model_index_by_name(const char *name)
{
    for (unsigned int i = 0; i < modelRegistryCount; i++)
    {
        if (strcmp(modelRegistry[i].name, name) == 0)
            return (int)i;
    }
    return -1;
}


// Makes `index` (into stageRegistry[]) the active stage: pulls its
// camera block into the live CAMERA struct, and resolves every object's
// model-name string against modelRegistry[] ONCE. Safe to call again
// with a different index for a runtime stage switch.
void load_stage(unsigned int index)
{
    activeStageObjectCount = 0;
    stageUnresolvedCount = 0;

    // Tear down the PREVIOUS stage's sounds before anything else: keys
    // their voices off and gives back their SPU RAM in reverse load order
    // (the bump allocator's LIFO contract). No-op on the first call.
    sfx_stage_unload();

    if (stageRegistryCount == 0)
    {
        // No assets/stage/*/stage.json were discovered at convert time -
        // camera stays at its compiled-in CAMERA default above, and
        // draw_stage() simply has zero objects to draw (and sfx has zero
        // sounds to play - unloaded above).
        activeStageIndex = 0;
        return;
    }

    if (index >= stageRegistryCount)
        index = 0;

    activeStageIndex = index;

    const STAGE_DEF *stage = &stageRegistry[activeStageIndex];

    camera.pos = stage->cameraPos;
    camera.rot = stage->cameraRot;

    unsigned int objectCount = stage->objectCount < MAX_STAGE_OBJECTS ? stage->objectCount : MAX_STAGE_OBJECTS;

    for (unsigned int i = 0; i < objectCount; i++)
    {
        int idx = find_model_index_by_name(stage->objects[i].model);

        // modelTriTextureCache[] only has slots for modelRegistry[0..
        // MAX_MODELS) - treat a model past that cap as "not found" so
        // draw_stage() never indexes it out of bounds.
        if (idx >= (int)MAX_MODELS)
            idx = -1;

        stageObjectModelIndex[i] = idx;
        if (idx < 0)
            stageUnresolvedCount++;
    }

    activeStageObjectCount = objectCount;

    // Load and (autoplay) start this stage's authored sounds - the CD
    // paths were baked from stage.json's "sounds" array by
    // py_convert_stages.py; a missing/bad file degrades to silence and
    // shows in the debug overlay's SFX UNRESOLVED count, same philosophy
    // as unresolved model names above. NOTE ordering at boot: init()
    // calls sound_init() and music_load() BEFORE the first load_stage(),
    // so stage sounds sit ABOVE the music bank in the SPU bump allocator
    // and a runtime stage switch can release them without touching music.
    sfx_stage_load(stage);
}



void init(void)
{
    // Reset GPU and install ISR subsystem
    ResetGraph(0);

    // Reset and enable the GTE. Must happen before any gte_* macro use.
    InitGeom();

    // Screen-space offset (where projected X=0,Y=0 lands on screen) and
    // projection plane distance. Replaces manual "SCREEN_CX + (vx*FOV)/z"
    // math that would otherwise be done by hand in draw_object_into_ot().
    gte_SetGeomOffset(SCREEN_CX, SCREEN_CY);
    gte_SetGeomScreen(FOCAL_LENGTH);

    // Define display environments, first on top and second on bottom
    SetDefDispEnv(&disp[0], 0,   0, DISPLAY_W, DISPLAY_H);
    SetDefDispEnv(&disp[1], 0, 240, DISPLAY_W, DISPLAY_H);

    // Define drawing environments, first on bottom and second on top
    SetDefDrawEnv(&draw[0], 0, 240, DISPLAY_W, DISPLAY_H);
    SetDefDrawEnv(&draw[1], 0,   0, DISPLAY_W, DISPLAY_H);

    // Set and enable clear colour (green background)
    setRGB0(&draw[0], 128, 128, 128);
    setRGB0(&draw[1], 128, 128, 128);
    draw[0].isbg = 1;
    draw[1].isbg = 1;

    // Clear double buffer counter
    db = 0;

    // Apply the GPU environments
    PutDispEnv(&disp[db]);
    PutDrawEnv(&draw[db]);

    // Load debug font
    FntLoad(960, 0);

    // Open up a debug font text stream of 500 characters
    FntOpen(0, 8, 320, 224, 0, 500);

    // Init pad (BIOS driver). Only padbuf[0] (controller 1) is actually
    // read by update() now - the BIOS pad driver still expects a second
    // buffer to be registered regardless, so padbuf[1] stays wired up
    // but unused for control (see update()'s own comment for the single-
    // controller, L2-modifier control scheme).
    InitPAD(padbuf[0], 34, padbuf[1], 34);
    StartPAD();

    // Don't clear pad data automatically; we read raw bytes ourselves
    ChangeClearPAD(0);

    // Upload every texture in the blob to VRAM and build the runtime
    // texture table. Must happen after ResetGraph() (which resets/clears
    // VRAM) but can otherwise go anywhere in init(); placed last here so
    // pad/font setup isn't visually blocked by it.
    load_textures();

    // Resolve every model's per-triangle material indices to texture
    // pointers once, now that both model data and textureTable[] are
    // loaded. Must run after load_textures(). Adding/removing a model
    // under assets/object/ picks this up automatically via modelRegistry[] - no
    // main.c edit needed.
    build_triangle_texture_cache();

    // Boot the SPU + CD (after ResetGraph/InitGeom, which CdInit/SpuInit
    // both depend on). Loads nothing itself anymore - sfx.c and music.c
    // do their own CD loads below; a drive error just leaves
    // sound_cd_ready() false and everything degrades to silence.
    sound_init();

    // Music is FULLY stage-authored now: it plays if - and only if - the
    // boot stage (stageRegistry[0]) places a mode=music sound entity,
    // whose baked cdPath/cdPath2 name the VAB/SEQ pair (assets/sound/
    // music/<SAMPLE>.VAB/.SEQ, shipped by py_convert_sounds.py). No
    // entity = no music_load() at all (overlay shows MUSIC LOADED=N) -
    // the old hardcoded \SONG fallback is gone, same arc the wind
    // ambient followed from hardcoded to stage-driven. The entity's
    // authored volume (baked 0..0x3fff) drives music_set_volume().
    // Peeked directly from the registry here - NOT via sfx_stage_music()
    // - because this must run BEFORE the first load_stage(): stage sfx
    // must sit ABOVE the music bank in the SPU bump allocator so a
    // runtime stage switch can LIFO-release them without clobbering
    // music's slice. (Swapping music ON a live stage transition - with
    // the entity's fadeOnStageEnter preference - is the future
    // transition system's job; it'll need a music unload/reload path
    // that respects that same LIFO order.) A missing/oversized/
    // malformed pair just leaves music_playing() false on the overlay.
    //
    // For MUSIC entities, Autoplay is the ENABLE toggle: a stage may
    // author several music entities and tick exactly the one it wants -
    // unticked ones are skipped entirely (not loaded, not blocking).
    // First ENABLED music entity wins, same rule as sfx_stage_music().
    // (Previously the first music entity won regardless of autoplay, so
    // a disabled first entity silently starved every later one.)
    if (stageRegistryCount > 0)
    {
        const STAGE_DEF *bootStage = &stageRegistry[0];
        for (unsigned int i = 0; i < bootStage->soundCount; i++)
        {
            const STAGE_SOUND *snd = &bootStage->sounds[i];
            if (snd->mode != SFX_MODE_MUSIC || !snd->autoplay)
                continue;

            if (music_load(snd->cdPath, snd->cdPath2))
            {
                music_set_volume(snd->volume, snd->volume);
                music_play();
            }
            break; // first ENABLED music entity wins
        }
    }

    // Make the first baked stage (stageRegistry[0]) active: pulls its
    // camera into `camera`, resolves every object's model name once, and
    // loads + starts the stage's authored sounds (see load_stage()) -
    // which is why this now runs LAST, after sound_init()/music_load().
    load_stage(0);

    // Resolve the third-person player model ONCE (name -> modelRegistry[]
    // index), same lookup stage objects use. -1 until assets/object/player/
    // player.obj has been baked in by py_convert_assets.py - draw_player()
    // no-ops on -1, so a not-yet-converted player just doesn't appear.
    playerModelIndex = find_model_index_by_name("player");
}


void display(void)
{
    // Flip buffer index
    db = !db;

    // Wait for all drawing to complete
    DrawSync(0);

    // Wait for vertical sync to cap the logic to 60fps (or 50 in PAL mode)
    VSync(0);

    // Switch pages
    PutDispEnv(&disp[db]);
    PutDrawEnv(&draw[db]);

    // Enable display output, ResetGraph() disables it by default
    SetDispMask(1);
}


uint8_t use_vertex_light = 1;

// Global "prefer textures when available" toggle. Note this is now a
// PREFERENCE, not a hard switch: draw_object_into_ot() only takes the
// textured path for a triangle when BOTH use_texture is on AND that
// triangle's resolved MODEL_TEXTURE is non-NULL (i.e. its material
// actually has a texture in the blob). A triangle whose material has no
// texture (flat-colour materials) always falls back to flat/Gouraud
// regardless of this flag - see draw_object_into_ot()'s per-triangle
// branch below.
uint8_t use_texture = 0;

// Live palette-row NUDGE, added on top of each placed object's own
// stage-authored base palette row (STAGE_OBJECT.palette) - see
// draw_stage(). Lets you cycle every object's palette together for
// testing (SQUARE/CIRCLE, camera schema - see update()) without having
// to re-author stage.json and reconvert just to preview a different
// row. draw_object_into_ot() clamps the COMBINED (object base + this
// nudge) value per-texture against that texture's own paletteCount, so
// this is safe to leave set higher than any given texture's row count.
uint8_t active_palette = 0;

// Positions the shared camera behind + above the player for the
// third-person view, at the current player_cam_yaw (which only changes
// while the user deliberately pans with the right stick - it never
// drifts on its own, so the world doesn't spin during normal movement).
// Locked to the player's XZ position every frame, keeping player and
// camera tied together. Called at the end of update() while PLAY mode
// is active, right before main() calls update_camera_matrix().
void update_player_follow_camera(void)
{
    // Local-frame offset: straight BACK (-Z) and UP, rotated by the pan
    // yaw. "Up" is -Y because the view matrix negates camera.pos - moving
    // camera.vy DOWN reads as UP everywhere else in this engine (see the
    // CAMERA schema's L1/R1).
    SVECTOR yawOnly = { 0, (short)player_cam_yaw, 0 };
    MATRIX yawMat;
    RotMatrix(&yawOnly, &yawMat);

    VECTOR off = { 0, -PLAYER_CAM_HEIGHT, -PLAYER_CAM_DIST };
    VECTOR rotOff;
    rotOff.vx = ((yawMat.m[0][0] * off.vx) + (yawMat.m[0][1] * off.vy) + (yawMat.m[0][2] * off.vz)) >> 12;
    rotOff.vy = ((yawMat.m[1][0] * off.vx) + (yawMat.m[1][1] * off.vy) + (yawMat.m[1][2] * off.vz)) >> 12;
    rotOff.vz = ((yawMat.m[2][0] * off.vx) + (yawMat.m[2][1] * off.vy) + (yawMat.m[2][2] * off.vz)) >> 12;

    camera.pos.vx = player_pos.vx + rotOff.vx;
    camera.pos.vy = player_pos.vy + rotOff.vy;
    camera.pos.vz = player_pos.vz + rotOff.vz;

    // Face the pan yaw so the player stays centred; player_cam_pitch tips
    // the view up/down (base 128/4096 ~ 11 deg down, right-stick Y nudges it).
    camera.rot.vx = (short)player_cam_pitch;
    camera.rot.vy = (short)player_cam_yaw;
    camera.rot.vz = 0;
}


// Edge detector shared by every latched toggle: true only on the frame a
// button goes released -> pressed (bit was 1 last frame, 0 now). One helper
// replaces the !(raw & X) && (prevPadRaw & X) that used to be copy-pasted
// per button. prevPadRaw is the single shared previous-frame state.
static int edge_pressed(unsigned short raw, unsigned short mask)
{
    return !(raw & mask) && (prevPadRaw & mask);
}

// ---- PLAY mode: the actual game (default on boot) ----
// Fully digital, nothing held. The D-pad moves the player camera-relative;
// L1/R1 orbit the follow-cam yaw around the player; L2/R2 pitch its view up/
// down. The face buttons are left free for player actions. Orbit and pitch
// are their own held controls, so moving and looking never fight.
static void update_play(unsigned short raw)
{
    playerSpawned = 1;   // idempotent - summon on first PLAY frame, then a no-op

    // L1/R1 orbit the follow-cam yaw; L2/R2 pitch the view (clamped). Pitch
    // DECREASES toward the sky (base 128 tilts slightly down), so L2 = up.
    if (!(raw & PAD_L1)) player_cam_yaw -= PLAYER_CAM_YAW_SPEED;   // orbit left
    if (!(raw & PAD_R1)) player_cam_yaw += PLAYER_CAM_YAW_SPEED;   // orbit right
    player_cam_yaw &= 4095;

    if (!(raw & PAD_L2)) player_cam_pitch -= PLAYER_CAM_PITCH_SPEED; // look up
    if (!(raw & PAD_R2)) player_cam_pitch += PLAYER_CAM_PITCH_SPEED; // look down
    if (player_cam_pitch < PLAYER_CAM_PITCH_MIN) player_cam_pitch = PLAYER_CAM_PITCH_MIN;
    if (player_cam_pitch > PLAYER_CAM_PITCH_MAX) player_cam_pitch = PLAYER_CAM_PITCH_MAX;

    // Movement: D-pad, treated as full deflection (+/-128) on each axis.
    int mx = 0, my = 0;
    if (!(raw & PAD_LEFT))  mx = -128;
    if (!(raw & PAD_RIGHT)) mx =  128;
    if (!(raw & PAD_UP))    my = -128;
    if (!(raw & PAD_DOWN))  my =  128;

    if (mx != 0 || my != 0)
    {
        // Camera-relative basis from the orbit yaw (same RotMatrix column
        // convention as the follow-cam), so D-pad UP always pushes the
        // player AWAY from the camera whatever the orbit.
        SVECTOR yawOnly = { 0, (short)player_cam_yaw, 0 };
        MATRIX yawMat;
        RotMatrix(&yawOnly, &yawMat);
        int fwdX = yawMat.m[0][2], fwdZ = yawMat.m[2][2];
        int rgtX = yawMat.m[0][0], rgtZ = yawMat.m[2][0];

        // forward f = up, strafe s = right; the /128 keeps the same world
        // units as before now that full deflection is a fixed +/-128.
        int f = -my, s = mx;
        player_pos.vx += ((fwdX * f + rgtX * s) / 128 * PLAYER_MOVE_SPEED) >> 12;
        player_pos.vz += ((fwdZ * f + rgtZ * s) / 128 * PLAYER_MOVE_SPEED) >> 12;

        // Face the direction of travel (OBJ files carry no look target, so
        // travel direction IS the look direction).
        player_rot.vx = 0;
        player_rot.vy = (short)((player_cam_yaw + fp_atan2(s, f)) & 4095);
        player_rot.vz = 0;
    }

    player_pos.vy = PLAYER_GROUND_Y;   // no gravity: locked to the ground plane
}

// ---- CAMERA mode: free-fly dev camera ----
// Fully digital. D-pad translates on the world X/Z plane, L1/R1 move on Y,
// L2/R2 yaw the view, TRIANGLE/CROSS pitch it, SQUARE/CIRCLE nudge the global
// palette row.
static void update_camera_mode(unsigned short raw)
{
    // Translate on the world X/Z plane.
    if (!(raw & PAD_UP))    camera.pos.vz += CAMERA_MOVE_SPEED; // forward
    if (!(raw & PAD_DOWN))  camera.pos.vz -= CAMERA_MOVE_SPEED; // backward
    if (!(raw & PAD_LEFT))  camera.pos.vx -= CAMERA_MOVE_SPEED; // strafe left
    if (!(raw & PAD_RIGHT)) camera.pos.vx += CAMERA_MOVE_SPEED; // strafe right

    // Y: L1 up, R1 down (view matrix negates camera.pos, so -vy reads up).
    if (!(raw & PAD_L1)) camera.pos.vy -= CAMERA_MOVE_SPEED; // up
    if (!(raw & PAD_R1)) camera.pos.vy += CAMERA_MOVE_SPEED; // down

    // Look: L2/R2 yaw, TRIANGLE/CROSS pitch.
    if (!(raw & PAD_R2)) camera.rot.vy += CAMERA_ROT_SPEED; // yaw right
    if (!(raw & PAD_L2)) camera.rot.vy -= CAMERA_ROT_SPEED; // yaw left
    if (!(raw & PAD_TRIANGLE)) camera.rot.vx -= CAMERA_ROT_SPEED; // pitch up
    if (!(raw & PAD_CROSS))    camera.rot.vx += CAMERA_ROT_SPEED; // pitch down
    camera.rot.vx &= 4095;
    camera.rot.vy &= 4095;

    // Palette row nudge - edge-detected, wraps 0-15 (per-TIM row ceiling).
    if (edge_pressed(raw, PAD_SQUARE)) active_palette = (active_palette + 1) & 0x0F;
    if (edge_pressed(raw, PAD_CIRCLE)) active_palette = (active_palette - 1) & 0x0F;
}

// ---- DEBUG mode: model / render inspector ----
// D-pad yaws (L/R) and pitches (U/D) the global debug transform, L1/R1 roll
// it, CROSS/CIRCLE drive FOV, TRIANGLE toggles lighting, SQUARE toggles
// texturing. 12-bit angles wrap via a power-of-two mask so rotation stays
// continuous through the 0/4096 boundary instead of snapping.
static void update_debug(unsigned short raw)
{
    // Pitch (X rotation): D-pad up/down.
    if (!(raw & PAD_UP))   model_rot.vx -= ROT_SPEED;
    if (!(raw & PAD_DOWN)) model_rot.vx += ROT_SPEED;
    model_rot.vx &= 4095;

    // Yaw (Y rotation): D-pad left/right.
    if (!(raw & PAD_LEFT))  model_rot.vy -= ROT_SPEED;
    if (!(raw & PAD_RIGHT)) model_rot.vy += ROT_SPEED;
    model_rot.vy &= 4095;

    // Roll (Z rotation): L1/R1.
    if (!(raw & PAD_L1)) model_rot.vz -= ROT_SPEED;
    if (!(raw & PAD_R1)) model_rot.vz += ROT_SPEED;
    model_rot.vz &= 4095;

    // FOV: CROSS widens, CIRCLE narrows.
    if (!(raw & PAD_CROSS))  fov += fov_speed;
    if (!(raw & PAD_CIRCLE)) fov -= fov_speed;
    if (fov > 65535) fov = 0;
    if (fov < -65535) fov = 65536;

    // Edge-detected render toggles.
    if (edge_pressed(raw, PAD_TRIANGLE)) use_vertex_light ^= 1;
    if (edge_pressed(raw, PAD_SQUARE))   use_texture ^= 1;
}

// Reads ONE controller (padbuf[0]) and drives whichever mode is latched.
// SELECT cycles the mode (edge-detected); each mode owns the whole pad, so
// there are no held modifiers any more. START (ambience) and L3 (overlay
// page) work in every mode. The follow-cam is only re-aimed in PLAY so the
// CAMERA mode's free-fly position is never overwritten.
void update(void)
{
    // bytes 2-3 contain button bits (little endian, 0 = pressed).
    // PadButton enums (PAD_UP, etc.) are bit masks where 1 = that
    // button, so we test with ! (pressed when bit is 0).
    unsigned short raw =
        *(unsigned short *)(padbuf[0] + 2);

    // SELECT cycles the latched mode: PLAY -> CAMERA -> DEBUG -> PLAY.
    if (edge_pressed(raw, PAD_SELECT))
        control_mode = (control_mode + 1) % MODE_COUNT;

    // Mode-entry hook: fires once on the frame we switch INTO a mode.
    // - PLAY:   zero the global debug transform so a stale MODEL rotation
    //           can't tilt the stage under the player.
    // - CAMERA: level the view to ROT 0,0,0. The PLAY follow-cam leaves
    //           camera.rot pitched toward the sky (player_cam_pitch), and
    //           CAMERA mode inherits that rotation, so reset it to a level
    //           starting point every time you tab in.
    static int prev_mode = MODE_PLAY;
    if (control_mode != prev_mode)
    {
        if (control_mode == MODE_PLAY)
        {
            model_rot.vx = 0; model_rot.vy = 0; model_rot.vz = 0;
            model_pos.vx = 0; model_pos.vy = 0; model_pos.vz = 0;
        }
        else if (control_mode == MODE_CAMERA)
        {
            camera.rot.vx = 0; camera.rot.vy = 0; camera.rot.vz = 0;
        }
        prev_mode = control_mode;
    }

    // Dispatch to the active mode's handler - each owns the whole pad.
    if      (control_mode == MODE_PLAY)   update_play(raw);
    else if (control_mode == MODE_CAMERA) update_camera_mode(raw);
    else                                  update_debug(raw);

    // ---- Mode-independent controls (fire in every mode) ----
    // L3 click cycles the debug overlay page. Requires the DualShock in
    // analog mode (red LED); in digital mode the L3 bit stays high and this
    // simply never fires.
    if (edge_pressed(raw, PAD_L3))
        debug_page = (debug_page + 1) % DEBUG_PAGE_COUNT;

    // START toggles the stage's ambient sounds on/off.
    if (edge_pressed(raw, PAD_START))
        sfx_stage_toggle();

    // Keep the follow-camera locked on the player only in PLAY. Left out of
    // the other modes on purpose so CAMERA's free-fly position survives.
    if (control_mode == MODE_PLAY && playerSpawned)
        update_player_follow_camera();

    prevPadRaw = raw;
}


// Builds camera_view_matrix from camera.pos/camera.rot. Built exactly
// ONCE per frame; each placed object's own world matrix (below) is
// rebuilt per object that frame, composing against this same view matrix.
void update_camera_matrix(void)
{
    // ---- Camera's view matrix (inverse rotation + inverse translation) ----
    // RotMatrix(&camera.rot, ...) gives the camera's OWN orientation; the
    // view matrix needs the inverse (transpose, since rotation matrices
    // are orthonormal) so that rotating the camera one way appears to
    // rotate the world the other way, exactly like an FPS camera.
    MATRIX camera_rot_matrix;
    RotMatrix(&camera.rot, &camera_rot_matrix);

    camera_view_matrix.m[0][0] = camera_rot_matrix.m[0][0];
    camera_view_matrix.m[0][1] = camera_rot_matrix.m[1][0];
    camera_view_matrix.m[0][2] = camera_rot_matrix.m[2][0];
    camera_view_matrix.m[1][0] = camera_rot_matrix.m[0][1];
    camera_view_matrix.m[1][1] = camera_rot_matrix.m[1][1];
    camera_view_matrix.m[1][2] = camera_rot_matrix.m[2][1];
    camera_view_matrix.m[2][0] = camera_rot_matrix.m[0][2];
    camera_view_matrix.m[2][1] = camera_rot_matrix.m[1][2];
    camera_view_matrix.m[2][2] = camera_rot_matrix.m[2][2];

    // Translation part of the view matrix is the transposed rotation
    // applied to -camera.pos (rotate the negated eye position by the
    // inverse rotation, rather than negating camera.pos directly, so
    // translate and rotate stay consistent when both change in one
    // frame). CAMERA_DISTANCE is folded into camera.pos's initial value,
    // not a separate hardcoded push here.
    VECTOR neg_cam_pos = { -camera.pos.vx, -camera.pos.vy, -camera.pos.vz };
    camera_view_matrix.t[0] =
        ((camera_view_matrix.m[0][0] * neg_cam_pos.vx) +
         (camera_view_matrix.m[0][1] * neg_cam_pos.vy) +
         (camera_view_matrix.m[0][2] * neg_cam_pos.vz)) >> 12;
    camera_view_matrix.t[1] =
        ((camera_view_matrix.m[1][0] * neg_cam_pos.vx) +
         (camera_view_matrix.m[1][1] * neg_cam_pos.vy) +
         (camera_view_matrix.m[1][2] * neg_cam_pos.vz)) >> 12;
    camera_view_matrix.t[2] =
        ((camera_view_matrix.m[2][0] * neg_cam_pos.vx) +
         (camera_view_matrix.m[2][1] * neg_cam_pos.vy) +
         (camera_view_matrix.m[2][2] * neg_cam_pos.vz)) >> 12;

    // Live FOV: keeps the GTE's projection distance in sync with the fov
    // variable (changed via PAD_CROSS/PAD_CIRCLE). Frame-global, not
    // per-object, so this only needs to happen once per frame.
    gte_SetGeomScreen(FOCAL_LENGTH + fov);
}


// Builds world_matrix (rotation + per-axis scale + translation) for ONE
// placed object, composes it against camera_view_matrix into
// composed_matrix, and loads that into the GTE. Called once per resolved
// object per frame, before that object's cull check, normal rotation,
// and triangle draw.
void update_object_world_and_compose(const VECTOR *pos, SVECTOR *rot, const VECTOR *scale)
{
    // ---- Object's own world matrix (rotation + scale + translation) ----
    // RotMatrix() takes a non-const SVECTOR* (psxgte.h), so `rot` can't be
    // const here even though this function never writes through it.
    RotMatrix(rot, &world_matrix);

    // Apply per-axis scale by scaling each COLUMN of the rotation matrix
    // (R * diag(scale) - scaling before rotating equals scaling each
    // rotated basis column). scale->v{x,y,z} are 4096-scaled fixed point
    // (4096 == 1.0), matching RotMatrix()'s own m[][] scale; >>12 keeps
    // each product in that same fixed point.
    for (int row = 0; row < 3; row++)
    {
        world_matrix.m[row][0] = (world_matrix.m[row][0] * scale->vx) >> 12;
        world_matrix.m[row][1] = (world_matrix.m[row][1] * scale->vy) >> 12;
        world_matrix.m[row][2] = (world_matrix.m[row][2] * scale->vz) >> 12;
    }

    world_matrix.t[0] = pos->vx;
    world_matrix.t[1] = pos->vy;
    world_matrix.t[2] = pos->vz;

    // ---- Compose camera_view_matrix * world_matrix -> composed_matrix ----
    // Standard view*model composition, spelled out by hand:
    //   composed_rotation    = camera_rotation * object_rotation
    //   composed_translation = camera_rotation * object_translation + camera_translation
    // psxgte.h's CompMatrixLV() does this same job in one call and could
    // replace this block, but that's a deliberate follow-up rather than
    // applied here, since this hand-rolled version is proven correct and
    // working at 60fps.
    for (int row = 0; row < 3; row++)
    {
        for (int col = 0; col < 3; col++)
        {
            composed_matrix.m[row][col] =
                ((camera_view_matrix.m[row][0] * world_matrix.m[0][col]) +
                 (camera_view_matrix.m[row][1] * world_matrix.m[1][col]) +
                 (camera_view_matrix.m[row][2] * world_matrix.m[2][col])) >> 12;
        }
    }

    composed_matrix.t[0] =
        (((camera_view_matrix.m[0][0] * world_matrix.t[0]) +
          (camera_view_matrix.m[0][1] * world_matrix.t[1]) +
          (camera_view_matrix.m[0][2] * world_matrix.t[2])) >> 12) + camera_view_matrix.t[0];
    composed_matrix.t[1] =
        (((camera_view_matrix.m[1][0] * world_matrix.t[0]) +
          (camera_view_matrix.m[1][1] * world_matrix.t[1]) +
          (camera_view_matrix.m[1][2] * world_matrix.t[2])) >> 12) + camera_view_matrix.t[1];
    composed_matrix.t[2] =
        (((camera_view_matrix.m[2][0] * world_matrix.t[0]) +
          (camera_view_matrix.m[2][1] * world_matrix.t[1]) +
          (camera_view_matrix.m[2][2] * world_matrix.t[2])) >> 12) + camera_view_matrix.t[2];

    gte_SetRotMatrix(&composed_matrix);
    gte_SetTransMatrix(&composed_matrix);
}


// Rotates one model's face + vertex normals into the shared
// transformedNormals/transformedVertNormals scratch arrays, using
// whatever composed_matrix is CURRENTLY loaded in the GTE (i.e. must be
// called right after update_object_world_and_compose() for the same
// object, with nothing else touching the GTE's rotation matrix in
// between).
void rotate_object_normals(const MODEL_DEF *model)
{
    unsigned int triCount = model->triCount < MAX_MODEL_TRIS ? model->triCount : MAX_MODEL_TRIS;

    // SVECTOR normals don't need translation, so this writes into
    // transformedNormals using gte_rtv0 (rotate-only) rather than
    // gte_rtps (rotate+translate+project).
    for (unsigned int i = 0; i < triCount; i++)
    {
        gte_ldv0(&model->faceNormals[i]);
        gte_rtv0();
        gte_stsv(&transformedNormals[i]);
    }

    if (use_vertex_light)
    {
        unsigned int vertCount = model->vertCount < MAX_MODEL_VERTS ? model->vertCount : MAX_MODEL_VERTS;

        for (unsigned int i = 0; i < vertCount; i++)
        {
            gte_ldv0(&model->vertNormals[i]);
            gte_rtv0();
            gte_stsv(&transformedVertNormals[i]);
        }
    }
}


// Transforms every unique vertex of `model` through the GTE exactly ONCE
// (gte_ldv0 + gte_rtps, the single-vertex rotate+translate+perspective
// op), caching each result's screen XY and screen Z into
// transformedScreenXY[]/transformedScreenSZ[]. draw_object_into_ot()
// then looks these up per triangle corner instead of re-running a fresh
// gte_rtpt() (the triple/per-triangle version) for every triangle - most
// vertices are referenced by more than one triangle, so this is strictly
// less GTE work than the old per-triangle transform, scaling with
// vertCount instead of 3x triCount. Must be called after
// update_object_world_and_compose() for this same object (needs
// composed_matrix current), same ordering requirement as
// rotate_object_normals() above.
void transform_object_vertices(const MODEL_DEF *model)
{
    unsigned int vertCount = model->vertCount < MAX_MODEL_VERTS ? model->vertCount : MAX_MODEL_VERTS;

    for (unsigned int i = 0; i < vertCount; i++)
    {
        gte_ldv0(&model->verts[i]);
        gte_rtps();
        gte_stsxy(&transformedScreenXY[i]);
        gte_stsz(&transformedScreenSZ[i]);
    }
}


// Projects this model's bounding sphere (centre + two radius-offset edge
// points along model-space X/Y) through composed_matrix - which MUST
// already be current for this object (call right after
// update_object_world_and_compose() for the SAME object) - and rejects
// the object if it's entirely outside what would actually be drawn.
// Uses the GTE's real rotate+translate+perspective pipeline (gte_rtpt)
// rather than an approximate CPU formula, so culling can't disagree with
// what the real projection would have produced.
//
// Returns nonzero if the object should be skipped entirely.
int object_is_culled(const MODEL_DEF *model)
{
    // Two points offset from the bounding-sphere centre by its own
    // radius along model-space X and Y - bsphereCenter/bsphereRadius are
    // in the same fixed-point space as modelVerts, so this is a plain
    // integer add. Cast to short since SVECTOR fields are 16-bit; a
    // radius large enough to overflow that would already be pushing
    // modelVerts' own 16-bit range, so this isn't a new risk.
    SVECTOR edgeX = {
        (short)(model->bsphereCenter->vx + model->bsphereRadius),
        model->bsphereCenter->vy,
        model->bsphereCenter->vz
    };
    SVECTOR edgeY = {
        model->bsphereCenter->vx,
        (short)(model->bsphereCenter->vy + model->bsphereRadius),
        model->bsphereCenter->vz
    };

    gte_ldv3(model->bsphereCenter, &edgeX, &edgeY);
    gte_rtpt();

    // Same near-plane threshold draw_object_into_ot() uses per-triangle.
    // If ALL THREE points are behind/at the near plane, treat the object
    // as not visible. If only some are invalid (straddling the near
    // plane), fall through and still draw it - safer to render something
    // we're unsure about than to wrongly cull a partly-visible object.
    uint32_t sz0, sz1, sz2;
    gte_stsz3(&sz0, &sz1, &sz2);

    if (sz0 < 64 && sz1 < 64 && sz2 < 64)
        return 1;

    DVECTOR sxy[3];
    gte_stsxy3(&sxy[0], &sxy[1], &sxy[2]);

    // Approximate on-screen radius as the larger of the two edge points'
    // screen-space offset from centre (not exact under perspective, so a
    // flat safety margin is added). Deliberately conservative: under-
    // culling wastes a little work, over-culling is a visible bug.
    int screenRadiusX = sxy[1].vx - sxy[0].vx;
    if (screenRadiusX < 0) screenRadiusX = -screenRadiusX;

    int screenRadiusY = sxy[2].vy - sxy[0].vy;
    if (screenRadiusY < 0) screenRadiusY = -screenRadiusY;

    int screenRadius = (screenRadiusX > screenRadiusY) ? screenRadiusX : screenRadiusY;
    screenRadius += 8; // flat safety margin, pixels

    if (sxy[0].vx + screenRadius < 0 || sxy[0].vx - screenRadius > DISPLAY_W ||
        sxy[0].vy + screenRadius < 0 || sxy[0].vy - screenRadius > DISPLAY_H)
        return 1;

    return 0;
}


// Draws one model instance's triangles by inserting each one into the
// shared Ordering Table (ot[db]) instead of calling DrawPrim() directly -
// the GPU's own DrawOTag() walk (see main()) back-to-front sorts every
// object's triangles together, so objects need no depth-sort pass of
// their own. Positions are NOT re-transformed here - transform_object_
// vertices() must already have cached this object's screen-space verts
// (same ordering requirement as rotate_object_normals()); this function
// only culls/buckets/emits primitives from that cache.
void draw_object_into_ot(const MODEL_DEF *model, MODEL_TEXTURE **triTextureCache, unsigned int objectPalette)
{
    unsigned int triCount = model->triCount < MAX_MODEL_TRIS ? model->triCount : MAX_MODEL_TRIS;

    for (unsigned int i = 0; i < triCount; i++)
    {
        MODEL_TRI *tri = &model->tris[i];

        // Look up this triangle's 3 corners from the cache
        // transform_object_vertices() already filled for the whole
        // object, instead of re-running gte_ldv3+gte_rtpt per triangle.
        const DVECTOR *p0 = &transformedScreenXY[tri->v0];
        const DVECTOR *p1 = &transformedScreenXY[tri->v1];
        const DVECTOR *p2 = &transformedScreenXY[tri->v2];

        // Backface cull: the same cross-product winding test gte_nclip()
        // computes in hardware -
        //   MAC0 = SX0*SY1 + SX1*SY2 + SX2*SY0 - SX0*SY2 - SX1*SY0 - SX2*SY1
        // - done here on the CPU against the cached screen coords, since
        // these 3 vertices are no longer freshly loaded into the GTE
        // together. The reject sign (>= 0) is the same one verified
        // against the arrow.obj winding test in the coordinate-system
        // block above - unchanged, just relocated off the GTE.
        int32_t cross =
            (int32_t)p0->vx * p1->vy + (int32_t)p1->vx * p2->vy + (int32_t)p2->vx * p0->vy -
            (int32_t)p0->vx * p2->vy - (int32_t)p1->vx * p0->vy - (int32_t)p2->vx * p1->vy;

        if (cross >= 0)
            continue;

        DVECTOR sxy[3] = { *p0, *p1, *p2 };

        // Near-plane reject, same threshold as before - read from the
        // per-vertex SZ cache instead of a fresh gte_stsz3().
        uint32_t sz0 = transformedScreenSZ[tri->v0];
        uint32_t sz1 = transformedScreenSZ[tri->v1];
        uint32_t sz2 = transformedScreenSZ[tri->v2];

        if (sz0 < 64 || sz1 < 64 || sz2 < 64)
            continue;

        // gte_ldsz3 feeds these 3 cached SZ values back into the GTE's
        // own SZ pipeline registers (no re-transform needed), so
        // gte_avsz3/gte_stotz still produce the exact same hardware-
        // scaled OTZ this project's OT_Z_SHIFT was tuned against.
        int otz;
        gte_ldsz3(sz0, sz1, sz2);
        gte_avsz3();
        gte_stotz(&otz);

        int bucket = otz >> OT_Z_SHIFT;
        if (bucket < 0) bucket = 0;
        if (bucket > OT_LEN - 1) bucket = OT_LEN - 1;

        // Resolve this triangle's texture, if any, from the cache built
        // once in build_triangle_texture_cache() (not per-frame). Takes
        // the textured path only if the global preference is on AND this
        // triangle's material actually has a texture; otherwise falls
        // back to flat/Gouraud.
        MODEL_TEXTURE *tex = (triTextureCache != NULL) ? triTextureCache[i] : NULL;

        // Every primitive gets its own slot bump-allocated from
        // primBuffer[db] (see nextpri's comment), checked against
        // sizeof(POLY_FT3) - the largest of the three types - so this
        // check is correct no matter which branch below runs.
        if (primBytesRemaining < (long)sizeof(POLY_FT3))
        {
            primOverflowCount++;
            continue;
        }

        if (use_texture && tex != NULL)
        {
            // Textured path: samples model->uvs[] (byte-scaled 0-255 PS1
            // GPU coords) and binds this triangle's resolved texture's
            // TPAGE/CLUT (tex->tim, resolved once at load time).
            //
            // Uses flat (one-normal-per-triangle) brightness rather than
            // per-vertex Gouraud, keeping the textured path independent
            // of use_vertex_light. Textured+Gouraud (POLY_GT3) is a
            // possible future variant, not wired up here.
            POLY_FT3 *pol = (POLY_FT3 *)nextpri;
            setPolyFT3(pol);

            SVECTOR *n = &transformedNormals[i];

            int brightness = n->vz >> 2;
            if (brightness < 0)
                brightness = -brightness;
            if (brightness > 255)
                brightness = 255;
            brightness += 32;
            if (brightness > 255)
                brightness = 255;

            // RGB here MODULATES the texture's own sampled colour (GPU
            // multiplies texel colour by this RGB) rather than replacing
            // it - same brightness value as the flat path, just applied
            // as a tint instead of a literal fill colour.
            setRGB0(pol, brightness, brightness, brightness);

            setXY3(
                pol,
                sxy[0].vx, sxy[0].vy,
                sxy[1].vx, sxy[1].vy,
                sxy[2].vx, sxy[2].vy
            );

            // tri->uv0/uv1/uv2 index into model->uvs[][2] (converter-
            // emitted, split-vertex space - same index space as
            // tri->v0/v1/v2).
            setUV3(
                pol,
                model->uvs[tri->uv0][0], model->uvs[tri->uv0][1],
                model->uvs[tri->uv1][0], model->uvs[tri->uv1][1],
                model->uvs[tri->uv2][0], model->uvs[tri->uv2][1]
            );

            // TPAGE/CLUT resolved once at texture-load time (in
            // load_textures(), stored in tex->tim), not recomputed per-
            // triangle-per-frame - tex->tim.mode is the colour-depth bits
            // GetTimInfo() already decoded from that texture's TIM header.
            setTPage(pol, tex->tim.mode & 0x3, 0, tex->tim.prect->x, tex->tim.prect->y);

            // Multi-CLUT row select: tim.crect->y is row 0's VRAM Y; row
            // k lives at crect->y + k (one 16-texel, 1-pixel-tall strip
            // per row). objectPalette is this object's stage-authored
            // base row plus the live active_palette nudge, clamped
            // against THIS texture's own paletteCount.
            unsigned int row = objectPalette;
            if (tex->paletteCount == 0)
                row = 0; // shouldn't happen (converter enforces clut_height >= 1) but don't underflow below
            else if (row >= tex->paletteCount)
                row = tex->paletteCount - 1;

            setClut(pol, tex->tim.crect->x, tex->tim.crect->y + row);

            addPrim(&ot[db][bucket], pol);
            nextpri += sizeof(POLY_FT3);
            primBytesRemaining -= sizeof(POLY_FT3);
        }
        else if (use_vertex_light)
        {
            // Gouraud path: one brightness per vertex, looked up from
            // transformedVertNormals via this triangle's own vertex
            // indices (tri->v0/v1/v2 - same indices used to load
            // positions above). The GPU interpolates between these 3
            // colours across the triangle face in hardware.
            POLY_G3 *pol = (POLY_G3 *)nextpri;
            setPolyG3(pol);

            SVECTOR *nv0 = &transformedVertNormals[tri->v0];
            SVECTOR *nv1 = &transformedVertNormals[tri->v1];
            SVECTOR *nv2 = &transformedVertNormals[tri->v2];

            int b0 = nv0->vz >> 2;
            int b1 = nv1->vz >> 2;
            int b2 = nv2->vz >> 2;

            if (b0 < 0) b0 = -b0;
            if (b1 < 0) b1 = -b1;
            if (b2 < 0) b2 = -b2;

            b0 += 32; if (b0 > 255) b0 = 255;
            b1 += 32; if (b1 > 255) b1 = 255;
            b2 += 32; if (b2 > 255) b2 = 255;

            setRGB0(pol, b0, b0, b0);
            setRGB1(pol, b1, b1, b1);
            setRGB2(pol, b2, b2, b2);

            setXY3(
                pol,
                sxy[0].vx, sxy[0].vy,
                sxy[1].vx, sxy[1].vy,
                sxy[2].vx, sxy[2].vy
            );

            addPrim(&ot[db][bucket], pol);
            nextpri += sizeof(POLY_G3);
            primBytesRemaining -= sizeof(POLY_G3);
        }
        else
        {
            // Flat path: one colour per triangle, from the precomputed,
            // GTE-rotated face normal built in rotate_object_normals().
            POLY_F3 *pol = (POLY_F3 *)nextpri;
            setPolyF3(pol);

            SVECTOR *n = &transformedNormals[i];

            int brightness = n->vz >> 2;
            if (brightness < 0)
                brightness = -brightness;
            if (brightness > 255)
                brightness = 255;
            brightness += 32;
            if (brightness > 255)
                brightness = 255;

            setRGB0(pol, brightness, brightness, brightness);

            setXY3(
                pol,
                sxy[0].vx, sxy[0].vy,
                sxy[1].vx, sxy[1].vy,
                sxy[2].vx, sxy[2].vy
            );

            addPrim(&ot[db][bucket], pol);
            nextpri += sizeof(POLY_F3);
            primBytesRemaining -= sizeof(POLY_F3);
        }
    }
}


// Resolves the ACTUAL per-frame pos/rot/scale for stage object `i` of
// the active stage: that object's own stage-authored transform, plus the
// global debug offset/multiplier (model_pos/model_rot/debug_scale) - see
// those variables' own comments.
static void get_object_transform(const STAGE_OBJECT *obj, VECTOR *outPos, SVECTOR *outRot, VECTOR *outScale)
{
    outPos->vx = obj->pos.vx + model_pos.vx;
    outPos->vy = obj->pos.vy + model_pos.vy;
    outPos->vz = obj->pos.vz + model_pos.vz;

    outRot->vx = (obj->rot.vx + model_rot.vx) & 4095;
    outRot->vy = (obj->rot.vy + model_rot.vy) & 4095;
    outRot->vz = (obj->rot.vz + model_rot.vz) & 4095;

    // Both obj->scale and debug_scale are 4096-scaled fixed point; combine
    // them with a fixed-point multiply (>>12) rather than just adding, so
    // debug_scale acts as a MULTIPLIER on top of each object's own scale
    // (e.g. debug_scale==8192 doubles whatever every object already had),
    // not an independent additive offset.
    outScale->vx = (obj->scale.vx * debug_scale) >> 12;
    outScale->vy = (obj->scale.vy * debug_scale) >> 12;
    outScale->vz = (obj->scale.vz * debug_scale) >> 12;
}


// Resolves and draws every placed object in the active stage into the
// shared OT (ot[db], reset by main() before this is called each frame).
//
// No object-level depth sort: draw_object_into_ot() inserts every
// triangle into ONE shared OT keyed by its own depth bucket, so the
// GPU's DrawOTag() walk (see main()) sorts every triangle from every
// object together - objects can be processed in any order. Per object:
// resolve its model (done once at stage load), build its matrix,
// frustum-cull it, and if visible, light + draw it.
void draw_stage(void)
{
    visibleObjectCount = 0;
    culledObjectCount = 0;

    if (activeStageIndex >= stageRegistryCount)
        return;

    const STAGE_DEF *stage = &stageRegistry[activeStageIndex];
    unsigned int objectCount = activeStageObjectCount;

    for (unsigned int i = 0; i < objectCount; i++)
    {
        int modelIndex = stageObjectModelIndex[i];
        if (modelIndex < 0)
        {
            // Unresolved model name (e.g. stage references "garage" but
            // assets/object/garage/garage.obj doesn't exist yet) - already
            // counted in stageUnresolvedCount at stage-load time; not
            // double-counted as "culled" here.
            continue;
        }

        const MODEL_DEF *model = &modelRegistry[modelIndex];
        const STAGE_OBJECT *obj = &stage->objects[i];

        VECTOR objPos, objScale;
        SVECTOR objRot;
        get_object_transform(obj, &objPos, &objRot, &objScale);

        update_object_world_and_compose(&objPos, &objRot, &objScale);

        if (object_is_culled(model))
        {
            culledObjectCount++;
            continue;
        }

        visibleObjectCount++;

        rotate_object_normals(model);
        transform_object_vertices(model);

        MODEL_TEXTURE **triTextureCache = modelTriTextureCache[modelIndex];
        unsigned int objectPalette = obj->palette + active_palette;

        draw_object_into_ot(model, triTextureCache, objectPalette);
    }
}


// Draws the runtime-summoned player through the same compose/cull/draw
// pipeline as stage objects, but OUTSIDE draw_stage()'s stage-object loop
// (the player isn't authored into any stage). No-ops until the player has
// been summoned (R2 schema) AND its model actually baked into
// modelRegistry[] (playerModelIndex >= 0). Shares the same OT/prim arena,
// so it depth-sorts against the stage naturally. Uses identity scale
// (4096) and the live active_palette, matching stage objects' palette nudge.
void draw_player(void)
{
    if (!playerSpawned || playerModelIndex < 0)
        return;

    const MODEL_DEF *model = &modelRegistry[playerModelIndex];

    VECTOR pos = { player_pos.vx, player_pos.vy, player_pos.vz };
    SVECTOR rot = { player_rot.vx, player_rot.vy, player_rot.vz };
    VECTOR scale = { 4096, 4096, 4096 };

    update_object_world_and_compose(&pos, &rot, &scale);

    if (object_is_culled(model))
    {
        culledObjectCount++;
        return;
    }

    visibleObjectCount++;

    rotate_object_normals(model);
    transform_object_vertices(model);

    MODEL_TEXTURE **triTextureCache = modelTriTextureCache[playerModelIndex];
    draw_object_into_ot(model, triTextureCache, active_palette);
}


// Print debug text to the screen. The readouts are split across
// DEBUG_PAGE_COUNT pages, cycled by the L3 click (see update()); only the
// active page's block prints each frame, so the overlay no longer buries
// the viewport. Every page shares a common header (schema + page number),
// then prints its own block:
//   page 0 - RENDER   (frame/stage/visibility/model counts)
//   page 1 - TRANSFORM+CAMERA+PLAYER (fov/rotation/camera/player state)
//   page 2 - AUDIO    (sfx/spu/music)
void debug_text(int counter)
{
    // Common header, always shown so the active mode and page are
    // visible regardless of which page's block is printing below.
    FntPrint(-1, "MODE=%s  PAGE %d/%d (SELECT=mode L3=page)\n",
        control_mode == MODE_PLAY   ? "PLAY"
            : control_mode == MODE_CAMERA ? "CAMERA" : "DEBUG",
        debug_page + 1, DEBUG_PAGE_COUNT);

    if (debug_page == 0)
    {
        // ---- Page 0: RENDER ----
        FntPrint(-1, "OBJ MODEL TEST (GTE)\n");
        FntPrint(-1, "FRAME=%d\n", counter);
        FntPrint(-1, "STAGE=%s OBJECTS=%d/%d UNRESOLVED=%d\n",
            (activeStageIndex < stageRegistryCount) ? stageRegistry[activeStageIndex].name : "(none)",
            activeStageObjectCount,
            (activeStageIndex < stageRegistryCount) ? stageRegistry[activeStageIndex].objectCount : 0,
            stageUnresolvedCount);
        FntPrint(-1, "VISIBLE=%d CULLED=%d PRIM_OVERFLOW=%d\n",
            visibleObjectCount, culledObjectCount, primOverflowCount);
        FntPrint(-1, "MODELS_BAKED=%d\n", modelRegistryCount);
        
        // Live projection distance: update_camera_matrix() pushes
        // FOCAL_LENGTH+fov into gte_SetGeomScreen() once per frame, so this
        // readout tracks the real GTE state (fov driven by CROSS/CIRCLE in
        // the debug schema).
        FntPrint(-1, "FOV=%d\n", FOCAL_LENGTH+fov);
        FntPrint(-1, "ROTX=%d ROTY=%d ROTZ=%d\n", model_rot.vx, model_rot.vy, model_rot.vz);
        FntPrint(-1, "DEBUGPOSOFFSET=%d,%d,%d\n", model_pos.vx, model_pos.vy, model_pos.vz);
        FntPrint(-1, "CAMPOS=%d,%d,%d CAMROTY=%d\n",
            camera.pos.vx, camera.pos.vy, camera.pos.vz, camera.rot.vy);
        FntPrint(-1, "VERTEXLIGHTING=%d TEXTURED=%d\n", use_vertex_light, use_texture);
        FntPrint(-1, "TEXTURES_LOADED=%d ACTIVE_PALETTE=%d\n", textureTableCount, active_palette);
        // Player state: whether summoned, its model resolution, XZ position
        // and orbit yaw. MODEL=-1 means player.obj hasn't been baked yet.
        FntPrint(-1, "PLAYER=%s MODEL=%d\n",
            playerSpawned ? "SPAWNED" : "(none)", playerModelIndex);
        FntPrint(-1, "PLAYERPOS=%d,%d,%d CAMYAW=%d\n",
            player_pos.vx, player_pos.vy, player_pos.vz, player_cam_yaw);

        // Stage-authored sounds (sfx.c): how many the stage authored vs. how
        // many actually made it off the CD into SPU RAM, the analogue of the
        // model-name UNRESOLVED count (missing .vag on disc, bad header, SPU
        // RAM/voice budget), and how many have latched silent via
        // muteAfterPlay. ON/OFF is the START-toggled master ambience.
        FntPrint(-1, "SFX=%s (START toggles) LOADED=%d/%d UNRES=%d MUTED=%d\n",
            sfx_stage_playing() ? "ON" : "OFF",
            sfx_stage_loaded_count(), sfx_stage_sound_count(),
            sfx_stage_unresolved_count(), sfx_stage_muted_count());

        // SPU RAM budget: bytes of waveform data resident vs. the ~508 KB usable
        // (512 KB minus the reserved capture area). PCT is used*100/capacity. As
        // more sound effects are added, watch this climb toward 100 - an upload
        // that would push past it is refused by the SPU bump allocator (the sound
        // just won't load) rather than corrupting another sample.
        FntPrint(-1, "SPU RAM=%d/%d B (%d%%)\n",
            sound_spu_used(), sound_spu_capacity(),
            (int)((sound_spu_used() * 100) / sound_spu_capacity()));

        // Music sequencer: playing/loaded state, voices currently keyed on (of
        // the 16-voice music pool), and the bank's share of the SPU RAM figure
        // above. LOADED=N means the SONG.VAB/SONG.SEQ pair didn't make it off
        // the disc (or failed to parse) - the game runs silently, same as WIND.
        FntPrint(-1, "MUSIC=%s LOADED=%s V=%d/%d BANK=%dB\n",
            music_playing() ? "ON" : "OFF",
            music_loaded() ? "Y" : "N",
            music_voices_active(), MUSIC_VOICE_COUNT,
            music_spu_used());
    }
    else if (debug_page == 1)
    {
        // ---- Page 1: TRANSFORM + CAMERA + PLAYER ----
        return;
    }
    else
    {
        // ---- Page 2: AUDIO ----
        return;
    }
}


// Main function, program entrypoint
int main(int argc, const char *argv[])
{
    int counter = 0;

    init();

    while (1)
    {
        update();

        // Camera-only matrix rebuild - once per frame, shared by every
        // object draw_stage() composes against this frame.
        update_camera_matrix();

        // Reset THIS frame's OT (ClearOTagR wires every bucket to link
        // to the next, all initially empty) and rewind the primitive
        // bump allocator - both keyed by the CURRENT db, matching
        // whichever draw environment display() left active last call.
        ClearOTagR(ot[db], OT_LEN);
        nextpri = primBuffer[db];
        primBytesRemaining = (long)sizeof(primBuffer[db]);
        primOverflowCount = 0;

        // Resolve, frustum-cull, and draw every placed object in the
        // active stage into ot[db] - replaces the old single-model
        // update_matrix()+sort_model()+draw_model() trio, and no longer
        // does its own CPU depth sort (the OT does that instead).
        draw_stage();

        // Draw the runtime-summoned third-person player (if any) into the
        // same OT, right after the stage objects so it depth-sorts against
        // them. No-ops until summoned via the R2 schema.
        draw_player();

        // Kick off the GPU's own back-to-front walk of everything
        // draw_stage() just queued into ot[db], starting from the
        // FARTHEST bucket (OT_LEN - 1) - this call itself is
        // non-blocking (just enqueues the GPU command), the actual wait
        // for it to finish happens in display()'s DrawSync(0) below.
        DrawOTag(ot[db] + (OT_LEN - 1));

        debug_text(counter);

        // Draw text LAST so it paints on top of every object's
        // primitives instead of being drawn first and then covered by
        // them - text and the OT triangles both just append to the same
        // GPU command sequence for this frame, so whatever's issued last
        // ends up on top.
        FntFlush(-1);

        display();

        // Advance the music sequencer exactly once per displayed frame -
        // display() has just synced to VBlank, which is the cadence the
        // sequencer's fixed-point tempo accumulator is calibrated against
        // (PAL/NTSC rate auto-detected in music.c at music_load() time).
        // Cheap no-op when nothing is playing.
        music_tick();

        // Advance the stage sfx layer at the same cadence: ONCE/INTERVAL
        // completion + re-fire timers, and the per-frame directional
        // falloff/pan pass - which is why the live camera goes in (yaw =
        // camera.rot.vy, the same 12-bit angle update() steers). Cheap
        // no-op while the ambience is stopped or the stage has no sounds.
        sfx_tick(&camera.pos, camera.rot.vy);

        counter++;
    }

    return 0;
}
