// root/main.c

/*
 * PSn00bSDK - OBJ Model Renderer (GTE version)
 *
 * Current features:
 * - Filled triangle rendering
 * - OBJ importer support
 * - Runtime scaling
 * - XYZ rotation (GTE-driven)
 * - GTE perspective projection
 * - GTE backface culling (gte_nclip)
 * - GTE-rotated face normals for flat lighting
 * - GTE-rotated vertex normals for Gouraud lighting
 * - Textured polygon rendering (POLY_FT3)
 * - Multi-CLUT palette-swap textures (stacked CLUT rows in one TIM,
 *   row selected globally via active_palette - pad 2 SQUARE/CIRCLE)
 * - Painter's Algorithm depth sorting (CPU, no OT yet)
 * - Double buffering
 *
 */

// Toolchain paths (set these as env vars on your machine, not hardcoded
// here - PATH, PSN00BPS1_TOOLS, PSN00BSDK_LIBS). See py_convert_assets.py
// and py_convert_textures.py for the asset-side equivalents.

#include <stdio.h>
#include <string.h>
#include <sys/types.h>

#include <psxetc.h>
#include <psxgte.h>
#include <psxgpu.h>
#include <psxapi.h>   // BIOS API: InitPAD, StartPAD, ChangeClearPAD, etc.
#include <psxpad.h>   // PadButton enums (PAD_UP, PAD_DOWN, PAD_LEFT, PAD_RIGHT)
#include <inline_c.h> // GTE macros (gte_ldv0, gte_rtpt, gte_nclip, etc.)


// #include "generated/arrow.c"
#include "generated/house.c"
// #include "generated/ball.c" // textured
// #include "generated/3shapes.c"
// #include "generated/honda.c"

// Concatenated texture blob (all TIMs back-to-back) + its offset/length
// table, both generated by py_convert_textures.py. tex_blob_start is the
// base pointer every offset in texBlobMaterialTable is relative to - this
// replaces the old single-texture face_tim_start[] + tim_face.S pair.
//
// TEX_BLOB_ENTRY (and the tex_blob_start/end + texBlobMaterialTable
// externs) now live in generated/tex_blob_table.h, not here - it used to
// be a hand-copied typedef in main.c that silently drifted out of sync
// with the generator's struct (missing paletteCount). One shared header
// now; see py_convert_textures.py's build_blob() for the generator side.
#include "generated/tex_blob_table.h"

// Runtime texture table - one resolved TIM_IMAGE per material name found
// in the blob. Built once in load_textures() at startup by walking
// texBlobMaterialTable and calling GetTimInfo() on each blob slice.
// Sized MAX_TEXTURES rather than texBlobEntryCount so it's a fixed-size
// array (simpler than a VLA/malloc on PS1); bump MAX_TEXTURES if this
// ever gets hit - MODEL_TRI.material is unsigned char so the real ceiling
// is 256, this is just today's practical cap.
#define MAX_TEXTURES 32

typedef struct
{
    const char *material;
    TIM_IMAGE tim;
    uint8_t loaded;

    // Number of stacked CLUT rows this texture actually has (1 if a
    // plain single-palette texture). Copied from the blob entry in
    // load_textures(); draw_model() clamps active_palette against this
    // per-texture before adding it to tim.crect->y, so a texture with
    // fewer rows than currently selected can't read past its own CLUT
    // block into another texture's VRAM data.
    unsigned int paletteCount;
} MODEL_TEXTURE;

static MODEL_TEXTURE textureTable[MAX_TEXTURES];
static unsigned int textureTableCount = 0;

// Per-model material name table (modelMaterialNames[]/modelMaterialCount),
// emitted by py_convert_assets.py from the .obj's usemtl lines, is
// #include'd above as part of generated/house.c. tri->material is an
// index into THAT array (per-model, first-seen order in the .obj) -
// draw_model() resolves modelMaterialNames[tri->material] (a name) against
// textureTable[] (also keyed by name) to find the actual TIM_IMAGE, if any.
// This indirection is what lets material index 0 mean different textures
// in different models safely.



// Screen consts (for model placement)
#define DISPLAY_W 320
#define DISPLAY_H 240

#define SCREEN_CX (DISPLAY_W / 2)
#define SCREEN_CY (DISPLAY_H / 2)



// ============================================================
// COORDINATE SYSTEM - FINALIZED (v4, verified via arrow.obj dual-tip test)
// ============================================================
// Source assets are authored in Blender, exported with Forward=-Z, Up=Y.
// The converter (py_convert_assets.py, get_split_vertex()) remaps every
// vertex/normal at export time so that:
//
//   renderer_X =  Blender_X
//   renderer_Y = -Blender_Z
//   renderer_Z = -Blender_Y
//
// Verified with a two-tipped arrow test object: Blender's +Y tip renders
// pointing AWAY from the camera; Blender's +Z tip renders pointing UP on
// screen. A model's Blender-up is screen-up, and its Blender-forward
// (+Y) points away from the camera by default with model_rot = {0,0,0} -
// no per-model rotation offset needed.
//
// Winding/cull sign (draw_model()'s gte_nclip/cross check) was
// re-verified against this final mapping: front-facing triangles are
// correctly kept with `if (cross >= 0) continue;` as the reject
// condition. If this coordinate block changes again, re-check that sign
// against the arrow.obj test - it flips whenever an even number of axes
// change sign, and stays put when an odd number do (a mnemonic, not a
// substitute for testing).
//
// Do NOT re-flip or re-derive axes anywhere else in this file. If a
// specific model renders mirrored or backwards, re-test with arrow.obj
// first - the bug is very likely elsewhere (a bad per-model rotation
// default, or that one asset having different OBJ export settings), not
// this coordinate system.
#define CAMERA_DISTANCE 4096
#define FOCAL_LENGTH    256
int fov = FOCAL_LENGTH;
int fov_speed = 10;

// Maximum number of vertices we cache for transformed model.
// Bumped from 127 -> 512 for Option B vertex-splitting at seams: a split
// model's vertex count can exceed its raw OBJ 'v' count (each hard-edge
// seam duplicates a position per distinct normal/UV it's used with). Check
// the converter's printed "Split vertex count" against this on each
// model swap - if a model ever exceeds 512, bump this again.
#define MAX_MODEL_VERTS 512

// Maximum number of triangles we cache for sorting/lighting.
#define MAX_MODEL_TRIS 256



// Double buffering
// Define display/draw environments for double buffering
DISPENV disp[2];
DRAWENV draw[2];
int db;



// Gamepad buffers (BIOS pad driver style)
static unsigned char padbuf[2][34];

// Previous frame's raw pad state, used for edge detection on toggle
// buttons (TRIANGLE/SQUARE) so a held button doesn't re-toggle every
// single frame (60x/sec) - only the released->pressed transition fires.
unsigned short prevPadRaw = 0xFFFF; // all-released, matches BIOS idle state



// ------------------------------------------------------------
// Camera
// ------------------------------------------------------------
// The GTE only ever transforms vertices relative to a fixed origin -
// there's no separate hardware concept of "moving a virtual eye". So
// "moving the camera" is implemented the same way "moving the world" was
// (translate/rotate vertices by the inverse of the camera's transform) -
// what's different here is WHERE that transform is accumulated: in one
// shared CAMERA struct, independent of any model's own transform, rather
// than baked into a single hardcoded world_matrix.t[] push. This is what
// lets multiple models (roadmap item) share one camera, and lets camera
// movement (also roadmap) touch only this struct instead of per-model code.
typedef struct
{
    VECTOR  pos;   // world-space position
    SVECTOR rot;   // 12-bit fixed-point angles (4096 = 360 degrees), same format as model_rot
} CAMERA;

CAMERA camera = { { 0, 0, -CAMERA_DISTANCE }, { 0, 0, 0 } };

const int32_t CAMERA_MOVE_SPEED = 32;   // world units per frame, same fixed-point scale as modelVerts
const uint16_t CAMERA_ROT_SPEED = 22;   // matches ROT_SPEED below for consistency

// Camera's own view matrix - rotation + translation for -camera.pos,
// rebuilt once per frame in update_matrix() from camera.pos/camera.rot.
// This is composed with each model's world matrix below rather than fed
// to the GTE directly - see update_matrix().
MATRIX camera_view_matrix;

// Composed matrix (camera_view_matrix * world_matrix) actually fed to the
// GTE each frame. Kept as its own variable (rather than overwriting
// world_matrix in place) so world_matrix always represents ONLY the
// model's own transform - important once multiple models exist and each
// needs to compose against the same camera_view_matrix independently.
MATRIX composed_matrix;



// Model state
// Runtime scale (divisor for fixed-point model coords)
int model_scale = 32;
const uint8_t SCALE_SPEED = 1;
const uint8_t ROT_SPEED = 22;

// XYZ rotation angles, fed straight into RotMatrix() as an SVECTOR.
// 12-bit fixed-point angle format (4096 = 360 degrees).
SVECTOR model_rot = { 0, 0, 0 };

// Independent model world-position (translation on top of rotation).
// Currently 0 by default - previously the "camera distance push" doubled
// as the model's only translation; now that the camera owns its own
// position, the model's translation is free to move independently (this
// is also the "Translation" roadmap item, unblocked by the same work).
VECTOR model_pos = { 0, 0, 0 };

// GTE rotation matrix, rebuilt once per frame from model_rot/model_pos.
// Represents ONLY the model's own transform - camera is composed in
// separately in update_matrix(), not baked in here.
MATRIX world_matrix;

// Screen-space output from gte_stsxy3, one DVECTOR triple per triangle.
DVECTOR screenVerts[3];

// Projected Z values (one per vertex of current tri), used for the
// near-plane skip and as the depth key (gte_avsz3) - this is also exactly
// what a future Ordering Table step would consume directly.
uint32_t projectedZ[3];

// Rotated face normal cache (one per triangle, post-transform).
// Index-matches modelFaceNormals (and modelTris) 1:1 - both arrays
// come from the same .obj export, so tri i's normal lives at [i] here.
SVECTOR transformedNormals[MAX_MODEL_TRIS];

// Rotated VERTEX normal cache (one per unique vertex position,
// post-transform). Index-matches modelVertNormals/modelVerts 1:1.
// Built once per frame in update_matrix() alongside the face normals,
// then looked up per-triangle-corner in draw_model() for Gouraud shading.
SVECTOR transformedVertNormals[MAX_MODEL_VERTS];

// Average view-space Z per triangle. Filled in by sort_model(),
// used as the sort key for the Painter's Algorithm.
int triDepth[MAX_MODEL_TRIS];

// Draw order: holds triangle indices (into modelTris/transformedNormals),
// sorted back-to-front by triDepth. draw_model() walks this array instead
// of walking modelTris in raw file order.
unsigned int triDrawOrder[MAX_MODEL_TRIS];

// Per-triangle resolved texture lookup cache. Index-matches modelTris 1:1.
// Filled once per model load (not per-frame - materials don't change at
// runtime) in build_triangle_texture_cache(): for each triangle, resolve
// modelMaterialNames[tri->material] against textureTable[] by name and
// cache a pointer to the matching MODEL_TEXTURE, or NULL if that material
// has no texture (flat-color material - draw_model() falls back to
// flat/Gouraud for those triangles instead of forcing POLY_FT3 on them).
// Doing this lookup once at load time instead of per-triangle-per-frame
// avoids a string-compare loop in the hot per-frame draw path.
static MODEL_TEXTURE *triTexture[MAX_MODEL_TRIS];



void load_textures(void)
{
    // Parses the concatenated blob (tex_blob_start[], baked in via
    // tex_blob.S's .incbin) using the offset table py_convert_textures.py
    // generated (texBlobMaterialTable[]/texBlobEntryCount). Each entry's
    // offset/length slices out one standalone TIM's bytes from the blob;
    // GetTimInfo() parses that slice exactly as it would a standalone
    // .tim file, since the blob is just N TIM files back-to-back with
    // no extra framing.
    textureTableCount = 0;

    for (unsigned int i = 0; i < texBlobEntryCount && textureTableCount < MAX_TEXTURES; i++)
    {
        const TEX_BLOB_ENTRY *entry = &texBlobMaterialTable[i];

        MODEL_TEXTURE *slot = &textureTable[textureTableCount];
        slot->material = entry->material;
        slot->paletteCount = entry->paletteCount;

        const unsigned char *tim_bytes = tex_blob_start + entry->offset;

        // GetTimInfo() expects a const uint32_t* - the blob is just raw
        // bytes, so this cast doesn't change layout, only how the pointer
        // is typed for the SDK call (same reasoning as the old single-
        // texture face_tim_start[] declaration).
        GetTimInfo((const uint32_t *)tim_bytes, &slot->tim);

        // Upload pixel data to VRAM at the rect the TIM specifies.
        LoadImage(slot->tim.prect, slot->tim.paddr);

        // Upload CLUT data to VRAM ONE ROW AT A TIME rather than as a
        // single N-row block. 4-bit TIMs always carry a CLUT (16 colors);
        // this would be skipped for a 24-bit direct-color TIM, but we're
        // 4-bit here so crect/caddr are always set for every entry in
        // this blob.
        //
        // A single LoadImage() covering all N rows at once hangs on
        // DuckStation (confirmed by bisection - never reproduced with a
        // single-row CLUT, which is all every texture before multi-CLUT
        // support ever had). Root cause not confirmed, suspected to be an
        // untested DMA block-chunking path in the SDK's _dma_transfer()
        // (libpsn00b/psxgpu/image.c). Splitting into N single-row (16x1)
        // transfers keeps every call on the same shape that already works
        // - if this reproduces on real hardware too, worth reporting
        // upstream to PSn00bSDK.
        if (slot->tim.crect != 0)
        {
            RECT clutRow = *slot->tim.crect;
            clutRow.h = 1;

            for (unsigned int row = 0; row < (unsigned int) slot->tim.crect->h; row++)
            {
                clutRow.y = slot->tim.crect->y + row;

                // caddr is a uint32_t* (2 packed 16-bit colors per word);
                // each 16-color row is 32 bytes = 8 words, so row k's
                // data starts 8*k words into caddr.
                LoadImage(&clutRow, slot->tim.caddr + (row * 8));
            }
        }

        slot->loaded = 1;
        textureTableCount++;
    }

    // Make sure every upload above has actually landed in VRAM before any
    // draw call tries to sample from them.
    DrawSync(0);
}


// Look up a texture by material name (linear scan - textureTableCount is
// small, typically single digits to low tens, so this is fine to do once
// per triangle at model-load time; see build_triangle_texture_cache()).
static MODEL_TEXTURE *find_texture_by_material(const char *material_name)
{
    for (unsigned int i = 0; i < textureTableCount; i++)
    {
        if (strcmp(textureTable[i].material, material_name) == 0)
            return &textureTable[i];
    }
    return NULL;
}


// Resolve every triangle's material index (tri->material, an index into
// THIS model's modelMaterialNames[]) to an actual texture pointer, once,
// at load time - not per-frame. Triangles whose material has no matching
// entry in textureTable[] (e.g. Grass0, which has no .tim of its own) get
// NULL here, which draw_model() treats as "use flat/Gouraud shading for
// this triangle" rather than a textured one.
void build_triangle_texture_cache(void)
{
    unsigned int triCount = modelTriCount < MAX_MODEL_TRIS ? modelTriCount : MAX_MODEL_TRIS;

    for (unsigned int i = 0; i < triCount; i++)
    {
        unsigned char material_index = modelTris[i].material;

        if (material_index >= modelMaterialCount)
        {
            // Shouldn't happen if py_convert_assets.py and this file
            // agree on MAX_MATERIALS_PER_MODEL, but fail safe to "no
            // texture" rather than reading out of bounds.
            triTexture[i] = NULL;
            continue;
        }

        const char *material_name = modelMaterialNames[material_index];
        triTexture[i] = find_texture_by_material(material_name);
    }
}



void init(void)
{
    // Reset GPU and install ISR subsystem
    ResetGraph(0);

    // Reset and enable the GTE. Must happen before any gte_* macro use.
    InitGeom();

    // Screen-space offset (where projected X=0,Y=0 lands on screen) and
    // projection plane distance. Replaces manual "SCREEN_CX + (vx*FOV)/z"
    // math that would otherwise be done by hand in draw_model().
    gte_SetGeomOffset(SCREEN_CX, SCREEN_CY);
    gte_SetGeomScreen(FOCAL_LENGTH);

    // Define display environments, first on top and second on bottom
    SetDefDispEnv(&disp[0], 0,   0, DISPLAY_W, DISPLAY_H);
    SetDefDispEnv(&disp[1], 0, 240, DISPLAY_W, DISPLAY_H);

    // Define drawing environments, first on bottom and second on top
    SetDefDrawEnv(&draw[0], 0, 240, DISPLAY_W, DISPLAY_H);
    SetDefDrawEnv(&draw[1], 0,   0, DISPLAY_W, DISPLAY_H);

    // Set and enable clear color (green background)
    setRGB0(&draw[0], 0, 96, 0);
    setRGB0(&draw[1], 0, 96, 0);
    draw[0].isbg = 1;
    draw[1].isbg = 1;

    // Clear double buffer counter
    db = 0;

    // Apply the GPU environments
    PutDispEnv(&disp[db]);
    PutDrawEnv(&draw[db]);

    // Load debug font
    FntLoad(960, 0);

    // Open up a debug font text stream of 200 characters
    FntOpen(0, 8, 320, 224, 0, 200);

    // Init pad (BIOS driver)
    InitPAD(padbuf[0], 34, padbuf[1], 34);
    StartPAD();

    // Don't clear pad data automatically; we read raw bytes ourselves
    ChangeClearPAD(0);

    // Upload every texture in the blob to VRAM and build the runtime
    // texture table. Must happen after ResetGraph() (which resets/clears
    // VRAM) but can otherwise go anywhere in init(); placed last here so
    // pad/font setup isn't visually blocked by it.
    load_textures();

    // Resolve this model's per-triangle material indices to texture
    // pointers once, now that both the model data and textureTable[] are
    // loaded. Must run after load_textures(). If you swap which model is
    // #include'd above, this picks up the new model's modelTris/
    // modelMaterialNames automatically - no per-model code change needed.
    build_triangle_texture_cache();
}


void display(void)
{
    // Flip buffer index
    db = !db;

    // Wait for all drawing to complete
    DrawSync(0);

    // Wait for vertical sync to cap the logic to 60fps (or 50 in PAL mode)
    VSync(0);

    // Switch pages
    PutDispEnv(&disp[db]);
    PutDrawEnv(&draw[db]);

    // Enable display output, ResetGraph() disables it by default
    SetDispMask(1);
}


uint8_t use_vertex_light = 1;

// Global "prefer textures when available" toggle. Note this is now a
// PREFERENCE, not a hard switch: draw_model() only takes the textured
// path for a triangle when BOTH use_texture is on AND that triangle's
// triTexture[i] is non-NULL (i.e. its material actually has a texture in
// the blob). A triangle whose material has no texture (flat-color
// materials) always falls back to flat/Gouraud regardless of this flag -
// see draw_model()'s per-triangle branch below.
uint8_t use_texture = 1;

// Which stacked CLUT row to bind for every textured triangle - a
// TEMPORARY global stand-in for a proper per-object selector. The
// eventual scene loader (scene.json sketches a "palette": N field per
// placed object) will need this per-instance instead, so two placed
// copies of the same texture can show different rows at once; one
// global is enough while only one model is ever on screen. Safe to
// leave set higher than a given texture's row count - draw_model()
// clamps per-texture against paletteCount (see MODEL_TEXTURE).
uint8_t active_palette = 0;

// Previous frame's raw pad-2 state, mirrors prevPadRaw but for controller
// 2. Needed now that pad 2 has its own edge-detected toggle (palette
// cycle) alongside its existing held-button camera controls.
unsigned short prevPadRaw2 = 0xFFFF;

// Read pad and update model scale/rotation
void update(void)
{
    // padbuf[0] = first controller
    // bytes 2-3 contain button bits (little endian, 0 = pressed)
    unsigned short raw =
        *(unsigned short *)(padbuf[0] + 2);

    // BIOS pad driver uses 0 = pressed, 1 = released.
    // PadButton enums (PAD_UP, etc.) are bit masks where 1 = that button.
    // So we test with ! (pressed when bit is 0).
    

    // Scale
    if (!(raw & PAD_UP)) model_scale -= SCALE_SPEED;
    if (!(raw & PAD_DOWN)) model_scale += SCALE_SPEED;
    if (model_scale < 1) model_scale = 1; // Clamp, avoids crash

    // XYZ rotation - 12-bit fixed-point angles (4096 = 360 degrees), so
    // the value space is circular, not bounded. A bitmask wrap (mod 4096,
    // since 4096 is a power of two) keeps rotation continuous through the
    // wraparound instead of snapping/popping at the boundary.
    if (!(raw & PAD_L1)) model_rot.vx -= ROT_SPEED;
    if (!(raw & PAD_R1)) model_rot.vx += ROT_SPEED;
    model_rot.vx &= 4095;

    if (!(raw & PAD_L2)) model_rot.vz -= ROT_SPEED;
    if (!(raw & PAD_R2)) model_rot.vz += ROT_SPEED;
    model_rot.vz &= 4095;

    if (!(raw & PAD_LEFT)) model_rot.vy -= ROT_SPEED;   // rotate left
    if (!(raw & PAD_RIGHT)) model_rot.vy += ROT_SPEED;   // rotate right
    model_rot.vy &= 4095;

    // FOV
    if (!(raw & PAD_CROSS)) fov += fov_speed;
    if (!(raw & PAD_CIRCLE)) fov -= fov_speed;
    if (fov > 65535) fov = 0;
    if (fov < -65535) fov = 65536;

    // Lighting mode toggle - only fire on the frame TRIANGLE goes from
    // released to pressed (bit was 1 last frame, is 0 this frame), not
    // on every frame it's held down.
    if (!(raw & PAD_TRIANGLE) && (prevPadRaw & PAD_TRIANGLE))
        use_vertex_light = use_vertex_light ^ 1;

    // Texture toggle - same edge-detected pattern as above.
    if (!(raw & PAD_SQUARE) && (prevPadRaw & PAD_SQUARE))
        use_texture = use_texture ^ 1;

    // ------------------------------------------------------------
    // Camera movement (pad 2 - pad 1 is fully claimed by model controls)
    // ------------------------------------------------------------
    // D-pad: translate on the world X/Z plane (strafe/forward-back).
    // L1/R1: translate on Y (up/down).
    // L2/R2: yaw (rotate around Y - "look left/right").
    // This is still a simple, direct mapping rather than a proper FPS-
    // style look-at/analog-stick camera (that refinement is still the
    // "Camera" roadmap item) but it's a real, usable control scheme now
    // rather than a one-axis scaffold - good enough to actually verify
    // the camera moves and rotates independently of the model.
    unsigned short raw2 =
        *(unsigned short *)(padbuf[1] + 2);

    if (!(raw2 & PAD_UP))    camera.pos.vz += CAMERA_MOVE_SPEED; // forward (into the scene)
    if (!(raw2 & PAD_DOWN))  camera.pos.vz -= CAMERA_MOVE_SPEED; // backward
    if (!(raw2 & PAD_LEFT))  camera.pos.vx -= CAMERA_MOVE_SPEED; // strafe left
    if (!(raw2 & PAD_RIGHT)) camera.pos.vx += CAMERA_MOVE_SPEED; // strafe right

    if (!(raw2 & PAD_L1)) camera.pos.vy -= CAMERA_MOVE_SPEED; // up
    if (!(raw2 & PAD_R1)) camera.pos.vy += CAMERA_MOVE_SPEED; // down

    if (!(raw2 & PAD_L2)) camera.rot.vy -= CAMERA_ROT_SPEED; // yaw left
    if (!(raw2 & PAD_R2)) camera.rot.vy += CAMERA_ROT_SPEED; // yaw right
    camera.rot.vy &= 4095;

    // Palette row cycle - edge-detected on pad 2 (pad 1 is claimed by
    // model controls). SQUARE/CIRCLE step through rows, wrapping 0-15
    // (the per-TIM row ceiling) rather than any one texture's real
    // paletteCount, since this is a single global shared by every
    // texture - draw_model() clamps per-texture on the output side,
    // this is just input.
    if (!(raw2 & PAD_SQUARE) && (prevPadRaw2 & PAD_SQUARE))
        active_palette = (active_palette + 1) & 0x0F;

    if (!(raw2 & PAD_CIRCLE) && (prevPadRaw2 & PAD_CIRCLE))
        active_palette = (active_palette - 1) & 0x0F;

    prevPadRaw = raw;
    prevPadRaw2 = raw2;
}


// Build this frame's rotation matrix and load it into the GTE.
// Replaces the old transform_model(): instead of pre-rotating every
// vertex and normal into a cached array up front, we just build the
// matrix once and let gte_rtps/gte_rtv0 do the per-vertex/per-normal work
// on demand inside draw_model().
//
// Camera composition: world_matrix represents ONLY the model's own
// rotation + position (model_rot/model_pos). camera_view_matrix
// represents the inverse of the camera's own rotation + position
// (camera.rot/camera.pos) - "inverse" because moving/rotating the
// camera forward is equivalent to moving/rotating every vertex in the
// world backward by the same amount; the GTE has no separate concept of
// a moving eye, only vertices transformed relative to a fixed origin.
// The two are combined into composed_matrix, which is what's actually
// fed to the GTE - this is what lets multiple models (roadmap item)
// each compose their own world_matrix against the SAME camera_view_matrix
// without duplicating camera logic per-model.
void update_matrix(void)
{
    // ---- Model's own world matrix (rotation + translation) ----
    RotMatrix(&model_rot, &world_matrix);
    world_matrix.t[0] = model_pos.vx;
    world_matrix.t[1] = model_pos.vy;
    world_matrix.t[2] = model_pos.vz;

    // ---- Camera's view matrix (inverse rotation + inverse translation) ----
    // RotMatrix(&camera.rot, ...) gives the camera's OWN orientation; the
    // view matrix needs the inverse (transpose, since rotation matrices
    // are orthonormal) so that rotating the camera one way appears to
    // rotate the world the other way, exactly like an FPS camera.
    MATRIX camera_rot_matrix;
    RotMatrix(&camera.rot, &camera_rot_matrix);

    camera_view_matrix.m[0][0] = camera_rot_matrix.m[0][0];
    camera_view_matrix.m[0][1] = camera_rot_matrix.m[1][0];
    camera_view_matrix.m[0][2] = camera_rot_matrix.m[2][0];
    camera_view_matrix.m[1][0] = camera_rot_matrix.m[0][1];
    camera_view_matrix.m[1][1] = camera_rot_matrix.m[1][1];
    camera_view_matrix.m[1][2] = camera_rot_matrix.m[2][1];
    camera_view_matrix.m[2][0] = camera_rot_matrix.m[0][2];
    camera_view_matrix.m[2][1] = camera_rot_matrix.m[1][2];
    camera_view_matrix.m[2][2] = camera_rot_matrix.m[2][2];

    // Translation part of the view matrix is the transposed rotation
    // applied to -camera.pos (standard view-matrix construction: rotate
    // the negated eye position by the inverse rotation, rather than just
    // negating camera.pos directly - this keeps translate and rotate
    // consistent when the camera is both moved AND rotated in the same
    // frame). CAMERA_DISTANCE is folded into camera.pos's initial value
    // (see the CAMERA struct default above) rather than being a separate
    // hardcoded push here, so the old single "shove everything back by a
    // constant" behavior is preserved as the camera's starting position,
    // not a separate code path.
    VECTOR neg_cam_pos = { -camera.pos.vx, -camera.pos.vy, -camera.pos.vz };
    camera_view_matrix.t[0] =
        ((camera_view_matrix.m[0][0] * neg_cam_pos.vx) +
         (camera_view_matrix.m[0][1] * neg_cam_pos.vy) +
         (camera_view_matrix.m[0][2] * neg_cam_pos.vz)) >> 12;
    camera_view_matrix.t[1] =
        ((camera_view_matrix.m[1][0] * neg_cam_pos.vx) +
         (camera_view_matrix.m[1][1] * neg_cam_pos.vy) +
         (camera_view_matrix.m[1][2] * neg_cam_pos.vz)) >> 12;
    camera_view_matrix.t[2] =
        ((camera_view_matrix.m[2][0] * neg_cam_pos.vx) +
         (camera_view_matrix.m[2][1] * neg_cam_pos.vy) +
         (camera_view_matrix.m[2][2] * neg_cam_pos.vz)) >> 12;

    // ---- Compose camera_view_matrix * world_matrix -> composed_matrix ----
    // Written out manually (rather than relying on a PSn00bSDK composition
    // helper whose exact signature/behavior I couldn't verify against
    // current SDK docs) so the math here is auditable and known-correct:
    // composed_rotation = camera_rotation * model_rotation (matrix product),
    // composed_translation = camera_rotation * model_translation + camera_translation
    // (transform the model's own translation into camera space, then add
    // the camera's own translation) - this is the standard view*model
    // composition, just spelled out instead of hidden behind a call whose
    // contract I'm not certain of. gte_SetRotMatrix/gte_SetTransMatrix take
    // whatever ends up in composed_matrix below.
    for (int row = 0; row < 3; row++)
    {
        for (int col = 0; col < 3; col++)
        {
            composed_matrix.m[row][col] =
                ((camera_view_matrix.m[row][0] * world_matrix.m[0][col]) +
                 (camera_view_matrix.m[row][1] * world_matrix.m[1][col]) +
                 (camera_view_matrix.m[row][2] * world_matrix.m[2][col])) >> 12;
        }
    }

    composed_matrix.t[0] =
        (((camera_view_matrix.m[0][0] * world_matrix.t[0]) +
          (camera_view_matrix.m[0][1] * world_matrix.t[1]) +
          (camera_view_matrix.m[0][2] * world_matrix.t[2])) >> 12) + camera_view_matrix.t[0];
    composed_matrix.t[1] =
        (((camera_view_matrix.m[1][0] * world_matrix.t[0]) +
          (camera_view_matrix.m[1][1] * world_matrix.t[1]) +
          (camera_view_matrix.m[1][2] * world_matrix.t[2])) >> 12) + camera_view_matrix.t[1];
    composed_matrix.t[2] =
        (((camera_view_matrix.m[2][0] * world_matrix.t[0]) +
          (camera_view_matrix.m[2][1] * world_matrix.t[1]) +
          (camera_view_matrix.m[2][2] * world_matrix.t[2])) >> 12) + camera_view_matrix.t[2];

    // Live FOV: keeps the GTE's projection distance in sync with the
    // fov variable, which update() changes via PAD_CROSS/PAD_CIRCLE.
    gte_SetGeomScreen(FOCAL_LENGTH + fov);

    gte_SetRotMatrix(&composed_matrix);
    gte_SetTransMatrix(&composed_matrix);

    // Rotate face normals using the same matrix. SVECTOR normals don't
    // need translation, so this writes into transformedNormals using
    // gte_rtv0 (rotate-only) rather than gte_rtps (rotate+translate+project).
    for (unsigned int i = 0; i < modelTriCount && i < MAX_MODEL_TRIS; i++)
    {
        gte_ldv0(&modelFaceNormals[i]);
        gte_rtv0();
        gte_stsv(&transformedNormals[i]);
    }

    if (use_vertex_light)
    {
        // Rotate per-vertex normals (modelVertNormals, one per split
        // vertex from the OBJ's vn data - see py_convert_assets.py).
        // Same rotate-only GTE call as above, just walking modelVertCount
        // instead of modelTriCount since this is one normal per unique
        // vertex slot rather than one per triangle.
        for (unsigned int i = 0; i < modelVertCount && i < MAX_MODEL_VERTS; i++)
        {
            gte_ldv0(&modelVertNormals[i]);
            gte_rtv0();
            gte_stsv(&transformedVertNormals[i]);
        }
    }
}


// Painter's Algorithm: compute each triangle's view-space depth and
// produce a back-to-front draw order. No Ordering Table yet (that's a
// future, hardware-assisted version of this same idea) - this is the
// plain CPU sort so triangles overlap correctly without one.
//
// Depth is derived by running each triangle's vertices through the GTE
// (gte_rtpt + gte_avsz3) rather than reading from a pre-rotated cache,
// since the GTE now rotates on demand instead of into a buffer up front.
void sort_model(void)
{
    for (unsigned int i = 0; i < modelTriCount && i < MAX_MODEL_TRIS; i++)
    {
        MODEL_TRI *tri = &modelTris[i];

        gte_ldv3(
            &modelVerts[tri->v0],
            &modelVerts[tri->v1],
            &modelVerts[tri->v2]
        );
        gte_rtpt();

        // gte_avsz3 gives the averaged, scaled Z of the three loaded
        // vertices in the OTZ register; pull it out with gte_stotz.
        gte_avsz3();
        gte_stotz(&triDepth[i]);

        triDrawOrder[i] = i;
    }

    // Simple insertion sort, descending by depth (farthest/largest Z
    // first, so painting proceeds back-to-front). Insertion sort is fine
    // here: triangle order barely changes frame-to-frame during rotation,
    // so each frame is close to an O(n) pass rather than O(n^2).
    unsigned int triCount = modelTriCount < MAX_MODEL_TRIS ? modelTriCount : MAX_MODEL_TRIS;

    for (unsigned int i = 1; i < triCount; i++)
    {
        unsigned int currentTri = triDrawOrder[i];
        int currentDepth = triDepth[currentTri];

        int j = i - 1;
        while (j >= 0 && triDepth[triDrawOrder[j]] < currentDepth)
        {
            triDrawOrder[j + 1] = triDrawOrder[j];
            j--;
        }
        triDrawOrder[j + 1] = currentTri;
    }
}


// Draw filled triangles for the transformed model.
// Walks triDrawOrder (built by sort_model) instead of modelTris directly,
// so triangles paint back-to-front - Painter's Algorithm.
//
// Rotation + projection + backface cull are all done per-triangle via
// the GTE rather than from a pre-transformed vertex/normal cache.
void draw_model(void)
{
    static POLY_F3 polyF;
    static POLY_G3 polyG;
    static POLY_FT3 polyFT;

    unsigned int triCount = modelTriCount < MAX_MODEL_TRIS ? modelTriCount : MAX_MODEL_TRIS;

    for (unsigned int order = 0; order < triCount; order++)
    {
        unsigned int i = triDrawOrder[order];

        MODEL_TRI *tri = &modelTris[i];

        // Load the three model-space vertices and run them through
        // rotate + translate + perspective (gte_rtpt = the "triple"
        // version of gte_rtps, does all 3 verts in one call).
        gte_ldv3(
            &modelVerts[tri->v0],
            &modelVerts[tri->v1],
            &modelVerts[tri->v2]
        );
        gte_rtpt();

        // gte_nclip computes the cross product of the screen-space
        // triangle:
        //   MAC0 = SX0*SY1 + SX1*SY2 + SX2*SY0 - SX0*SY2 - SX1*SY0 - SX2*SY1
        // same winding test as a manual cross-product backface cull.
        // gte_stopz reads MAC0 (COP2 register $24) back into a C variable.
        gte_nclip();

        int32_t cross;
        gte_stopz(&cross);

        if (cross >= 0)
            continue;

        // Pull projected screen XY for all 3 vertices in one go.
        gte_stsxy3(&screenVerts[0], &screenVerts[1], &screenVerts[2]);

        // Near-plane reject: gte_rtpt already divides by Z internally,
        // so rather than checking raw Z here we rely on the SZ (screen Z)
        // values pulled via gte_stsz3 for the "too close, skip" check.
        uint32_t sz0, sz1, sz2;
        gte_stsz3(&sz0, &sz1, &sz2);

        if (sz0 < 64 || sz1 < 64 || sz2 < 64)
            continue;

        // Resolve this triangle's texture, if any, from the cache built
        // once in build_triangle_texture_cache() - NOT a per-frame
        // lookup. A triangle only takes the textured path if the global
        // preference is on AND this specific triangle's material
        // actually has a texture; otherwise it falls back to flat/Gouraud
        // exactly as a texture-less material always would.
        MODEL_TEXTURE *tex = triTexture[i];

        if (use_texture && tex != NULL)
        {
            // Textured path: samples modelUVs[] (byte-scaled 0-255 PS1 GPU
            // coords, written by the converter from the OBJ's vt data) and
            // binds this triangle's own resolved texture's TPAGE/CLUT
            // (tex->tim, resolved once at load time from the blob) -
            // rather than a single global faceTexture as before, each
            // triangle now binds whichever texture its OWN material
            // resolved to.
            //
            // Uses the flat (one-normal-per-triangle) brightness calc
            // rather than per-vertex Gouraud - this keeps the textured
            // path independent of use_vertex_light for now. A
            // textured+Gouraud (POLY_GT3) combination is a possible
            // future variant but isn't wired up here.
            setPolyFT3(&polyFT);

            SVECTOR *n = &transformedNormals[i];

            int brightness = n->vz >> 2;
            if (brightness < 0)
                brightness = -brightness;
            if (brightness > 255)
                brightness = 255;
            brightness += 32;
            if (brightness > 255)
                brightness = 255;

            // RGB here MODULATES the texture's own sampled color (GPU
            // multiplies texel color by this RGB) rather than replacing
            // it - same brightness value as the flat path, just applied
            // as a tint instead of a literal fill color.
            setRGB0(&polyFT, brightness, brightness, brightness);

            setXY3(
                &polyFT,
                screenVerts[0].vx, screenVerts[0].vy,
                screenVerts[1].vx, screenVerts[1].vy,
                screenVerts[2].vx, screenVerts[2].vy
            );

            // tri->uv0/uv1/uv2 index into modelUVs[][2] (converter-emitted,
            // split-vertex space - same index space as tri->v0/v1/v2).
            setUV3(
                &polyFT,
                modelUVs[tri->uv0][0], modelUVs[tri->uv0][1],
                modelUVs[tri->uv1][0], modelUVs[tri->uv1][1],
                modelUVs[tri->uv2][0], modelUVs[tri->uv2][1]
            );

            // TPAGE/CLUT resolved once at texture-load time (in
            // load_textures(), stored in tex->tim), not recomputed per-
            // triangle-per-frame - tex->tim.mode is the color-depth bits
            // GetTimInfo() already decoded from that texture's TIM header.
            setTPage(&polyFT, tex->tim.mode & 0x3, 0, tex->tim.prect->x, tex->tim.prect->y);

            // Multi-CLUT row select: tim.crect->y is row 0's VRAM Y (fixed
            // at load time); row k lives at crect->y + k, one scanline per
            // row (each row is a 16-texel-wide, 1-pixel-tall strip - see
            // TIM_FILEFORMAT_SEMANTICS.txt). Clamp active_palette against
            // THIS texture's own paletteCount, not just 0-15, since
            // active_palette is a single global shared across every
            // texture and this one texture may have fewer rows than
            // whatever's currently selected.
            unsigned int row = active_palette;
            if (tex->paletteCount == 0)
                row = 0; // shouldn't happen (converter enforces clut_height >= 1) but don't underflow below
            else if (row >= tex->paletteCount)
                row = tex->paletteCount - 1;

            setClut(&polyFT, tex->tim.crect->x, tex->tim.crect->y + row);

            DrawPrim((uint32_t *)&polyFT);
        }
        else if (use_vertex_light)
        {
            // Gouraud path: one brightness per vertex, looked up from
            // transformedVertNormals via this triangle's own vertex
            // indices (tri->v0/v1/v2 - same indices used to load
            // positions above). The GPU interpolates between these 3
            // colors across the triangle face in hardware.
            setPolyG3(&polyG);

            SVECTOR *nv0 = &transformedVertNormals[tri->v0];
            SVECTOR *nv1 = &transformedVertNormals[tri->v1];
            SVECTOR *nv2 = &transformedVertNormals[tri->v2];

            int b0 = nv0->vz >> 2;
            int b1 = nv1->vz >> 2;
            int b2 = nv2->vz >> 2;

            if (b0 < 0) b0 = -b0;
            if (b1 < 0) b1 = -b1;
            if (b2 < 0) b2 = -b2;

            b0 += 32; if (b0 > 255) b0 = 255;
            b1 += 32; if (b1 > 255) b1 = 255;
            b2 += 32; if (b2 > 255) b2 = 255;

            setRGB0(&polyG, b0, b0, b0);
            setRGB1(&polyG, b1, b1, b1);
            setRGB2(&polyG, b2, b2, b2);

            setXY3(
                &polyG,
                screenVerts[0].vx, screenVerts[0].vy,
                screenVerts[1].vx, screenVerts[1].vy,
                screenVerts[2].vx, screenVerts[2].vy
            );

            DrawPrim((uint32_t *)&polyG);
        }
        else
        {
            // Flat path: one color per triangle, from the precomputed,
            // GTE-rotated face normal built in update_matrix().
            setPolyF3(&polyF);

            SVECTOR *n = &transformedNormals[i];

            int brightness = n->vz >> 2;
            if (brightness < 0)
                brightness = -brightness;
            if (brightness > 255)
                brightness = 255;
            brightness += 32;
            if (brightness > 255)
                brightness = 255;

            setRGB0(&polyF, brightness, brightness, brightness);

            setXY3(
                &polyF,
                screenVerts[0].vx, screenVerts[0].vy,
                screenVerts[1].vx, screenVerts[1].vy,
                screenVerts[2].vx, screenVerts[2].vy
            );

            DrawPrim((uint32_t *)&polyF);
        }
    }
}


// Print debug text to the screen
void debug_text(int counter)
{
    FntPrint(-1, "OBJ MODEL TEST (GTE)\n");
    FntPrint(-1, "FRAME=%d\n", counter);

    FntPrint(-1, "SCALE=%d\n", model_scale);
    // NOTE: this prints FOCAL_LENGTH+fov as if it's the live projection
    // distance, but see the comment above update() - fov currently isn't
    // fed back into gte_SetGeomScreen(), so this number moves while the
    // actual FOV does not. Either wire fov into the GTE each frame or
    // drop it from this readout until that's done.
    FntPrint(-1, "FOV=%d\n", FOCAL_LENGTH+fov);
    FntPrint(-1, "ROTX=%d\n", model_rot.vx);
    FntPrint(-1, "ROTY=%d\n", model_rot.vy);
    FntPrint(-1, "ROTZ=%d\n", model_rot.vz);
    FntPrint(-1, "MODELPOS=%d,%d,%d\n", model_pos.vx, model_pos.vy, model_pos.vz);
    FntPrint(-1, "CAMPOS=%d,%d,%d\n", camera.pos.vx, camera.pos.vy, camera.pos.vz);
    FntPrint(-1, "CAMROTY=%d\n", camera.rot.vy);
    FntPrint(-1, "VERTEXLIGHTING=%d\n", use_vertex_light);
    FntPrint(-1, "TEXTURED=%d\n", use_texture);
    FntPrint(-1, "TEXTURES_LOADED=%d\n", textureTableCount);
    FntPrint(-1, "ACTIVE_PALETTE=%d\n", active_palette);
}


// Main function, program entrypoint
int main(int argc, const char *argv[])
{
    int counter = 0;

    init();

    while (1)
    {
        update();

        // Build this frame's rotation matrix and load it into the GTE
        // (replaces the old transform_model() vertex/normal pre-pass)
        update_matrix();

        // Depth-sort triangles back-to-front (Painter's Algorithm)
        sort_model();

        // Draw model (rotation + projection + backface cull all via GTE)
        draw_model();

        debug_text(counter);

        // Draw text LAST so it paints on top of the model's primitives
        // instead of being drawn first and then covered by them - text
        // and primitives both just append to the same GPU command
        // sequence for this frame, so whatever's issued last ends up on top.
        FntFlush(-1);

        display();

        counter++;
    }

    return 0;
}